CREATE TABLE [dbo].[01_realised_all] (
    [Trade Deal Number]               VARCHAR (100) NULL,
    [Trade Reference Text]            VARCHAR (400) NULL,
    [Transaction Info Status]         VARCHAR (100) NULL,
    [Instrument Toolset Name]         VARCHAR (100) NULL,
    [Instrument Type Name]            VARCHAR (100) NULL,
    [Int Legal Entity Name]           VARCHAR (100) NULL,
    [Int Business Unit Name]          VARCHAR (100) NULL,
    [Internal Portfolio Business Key] VARCHAR (100) NULL,
    [Desk Name]                       VARCHAR (100) NULL,
    [Intermediate1 Name]              VARCHAR (100) NULL,
    [Book Name]                       VARCHAR (100) NULL,
    [Internal Portfolio Name]         VARCHAR (100) NULL,
    [External Portfolio Name]         VARCHAR (100) NULL,
    [Ext Business Unit Name]          VARCHAR (100) NULL,
    [Ext Legal Entity Name]           VARCHAR (100) NULL,
    [Index Name]                      VARCHAR (100) NULL,
    [Trade Currency]                  VARCHAR (100) NULL,
    [Transaction Info Buy Sell]       VARCHAR (100) NULL,
    [Cashflow Type]                   VARCHAR (100) NULL,
    [Cashflow Settlement Type]        VARCHAR (100) NULL,
    [Side Pipeline Name]              VARCHAR (100) NULL,
    [Instrument Subtype Name]         VARCHAR (100) NULL,
    [Discounting Index Name]          VARCHAR (100) NULL,
    [Trade Price]                     FLOAT (53)    NULL,
    [Document Number]                 VARCHAR (100) NULL,
    [Cashflow Delivery Month]         VARCHAR (100) NULL,
    [Trade Date]                      DATETIME      NULL,
    [Index Contract Size]             FLOAT (53)    NULL,
    [Discounting Index Contract Size] VARCHAR (100) NULL,
    [Trade Instrument Reference Text] VARCHAR (100) NULL,
    [Unit Name (Trade Std)]           VARCHAR (100) NULL,
    [Leg Exercise Date]               DATETIME      NULL,
    [Cashflow Payment Date]           DATETIME      NULL,
    [Leg End Date]                    DATETIME      NULL,
    [Delivery Month]                  VARCHAR (100) NULL,
    [Index Group]                     VARCHAR (100) NULL,
    [Delivery Vessel Name]            VARCHAR (50)  NULL,
    [Static Ticket ID]                VARCHAR (50)  NULL,
    [Source Of Row]                   VARCHAR (100) NULL,
    [COB]                             DATE          NULL,
    [Desk Currency]                   VARCHAR (50)  NULL,
    [volume]                          FLOAT (53)    NULL,
    [Realised_OrigCCY_Undisc]         FLOAT (53)    NULL,
    [Realised_OrigCCY_Disc]           FLOAT (53)    NULL,
    [Realised_DeskCCY_Undisc]         FLOAT (53)    NULL,
    [Realised_DeskCCY_Disc]           FLOAT (53)    NULL,
    [Realised_EUR_Undisc]             FLOAT (53)    NULL,
    [Realised_EUR_Disc]               FLOAT (53)    NULL,
    [Realised_GBP_Undisc]             FLOAT (53)    NULL,
    [Realised_GBP_Disc]               FLOAT (53)    NULL,
    [Realised_USD_Undisc]             FLOAT (53)    NULL,
    [Realised_USD_Disc]               FLOAT (53)    NULL,
    [ToBeDeleted]                     INT           CONSTRAINT [DF_01_realised_all_ROCK_ToBeDeleted] DEFAULT ((0)) NULL,
    [Comment]                         VARCHAR (255) NULL,
    [FileID]                          INT           NULL,
    [LastUpdate]                      DATETIME      CONSTRAINT [DF_01_realised_all_ROCK_LastUpdate] DEFAULT (getdate()) NULL
);


GO

