CREATE TABLE [dbo].[02_Realised_all_details] (
    [ID]                      INT             IDENTITY (1, 1) NOT NULL,
    [group]                   VARCHAR (100)   NULL,
    [ctpygroup]               VARCHAR (100)   NULL,
    [IntDesk]                 VARCHAR (100)   NULL,
    [Commodity]               VARCHAR (100)   NULL,
    [OrderNo]                 VARCHAR (100)   NULL,
    [UNIT_TO]                 VARCHAR (100)   NULL,
    [Volume_new]              FLOAT (53)      NULL,
    [Deal]                    VARCHAR (100)   NULL,
    [Reference]               VARCHAR (100)   NULL,
    [Tran Status]             VARCHAR (100)   NULL,
    [Toolset]                 VARCHAR (255)   NULL,
    [InstrumentType]          VARCHAR (100)   NULL,
    [Group ID]                VARCHAR (255)   NULL,
    [InternalLegalEntity]     VARCHAR (100)   NULL,
    [InternalBusinessUnit]    VARCHAR (100)   NULL,
    [PfID]                    VARCHAR (100)   NULL,
    [InternalPortfolio]       VARCHAR (100)   NULL,
    [Pf Group]                VARCHAR (255)   NULL,
    [ExternalBusinessUnit]    VARCHAR (100)   NULL,
    [ExternalLegalEntity]     VARCHAR (100)   NULL,
    [ExternalPortfolio]       VARCHAR (100)   NULL,
    [ProjectionIndex]         VARCHAR (100)   NULL,
    [Currency]                VARCHAR (5)     NULL,
    [Action]                  VARCHAR (5)     NULL,
    [Volume]                  NUMERIC (20, 3) NULL,
    [Unit]                    VARCHAR (100)   NULL,
    [DocumentNumber]          INT             NULL,
    [EventDate]               VARCHAR (100)   NULL,
    [TradeDate]               DATETIME        NULL,
    [CashflowDeliveryMonth]   DATETIME        NULL,
    [DeliveryMonth]           VARCHAR (100)   NULL,
    [FXRate]                  FLOAT (53)      NULL,
    [Realised]                NUMERIC (20, 2) NULL,
    [RealisedBase]            NUMERIC (20, 2) NULL,
    [CashflowType]            VARCHAR (100)   NULL,
    [InstrumentSubType]       VARCHAR (100)   NULL,
    [PowerRegion]             VARCHAR (255)   NULL,
    [Pipeline]                VARCHAR (100)   NULL,
    [Delivery Vessel Name]    VARCHAR (50)    NULL,
    [Static Ticket ID]        VARCHAR (50)    NULL,
    [DiscountingIndex]        VARCHAR (100)   NULL,
    [Ticker]                  VARCHAR (100)   NULL,
    [TradePrice]              VARCHAR (100)   NULL,
    [LiquidityReport_ccy]     FLOAT (53)      NULL,
    [SAP_Account]             VARCHAR (100)   NULL,
    [Realized_CCY_Futures]    FLOAT (53)      NULL,
    [Ref3]                    VARCHAR (5)     NULL,
    [LegalEntity]             VARCHAR (100)   NULL,
    [Partner]                 VARCHAR (255)   NULL,
    [StKZ_zw1]                VARCHAR (255)   NULL,
    [StKZ]                    VARCHAR (255)   NULL,
    [VAT_CountryCode]         VARCHAR (255)   NULL,
    [Desk Currency]           VARCHAR (100)   NULL,
    [Realized_YTD_EUR_disc]   FLOAT (53)      NULL,
    [Realised_DeskCCY_disc]   FLOAT (53)      NULL,
    [Realized_YTD_GBP_disc]   FLOAT (53)      NULL,
    [Realized_YTD_USD_disc]   FLOAT (53)      NULL,
    [Realized_YTD_EUR_undisc] FLOAT (53)      NULL,
    [Realised_DeskCCY_Undisc] FLOAT (53)      NULL,
    [Realized_YTD_GBP_undisc] FLOAT (53)      NULL,
    [Realized_YTD_USD_undisc] FLOAT (53)      NULL,
    [LegExerciseDate]         DATETIME        NULL,
    [LegEndDate]              DATETIME        NULL,
    [UpdateKonten]            VARCHAR (255)   NULL,
    [FileID]                  INT             NULL,
    CONSTRAINT [pk_02_Realised_all_details_Rock] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

