CREATE TABLE [dbo].[Realised Pnl-GloRi-Data] (
    [Trade Deal Number]                               NVARCHAR (100) NULL,
    [Trade Reference Text]                            NVARCHAR (400) NULL,
    [Transaction Info Status]                         NVARCHAR (100) NULL,
    [Instrument Toolset Name]                         NVARCHAR (100) NULL,
    [Instrument Type Name]                            NVARCHAR (100) NULL,
    [Int Legal Entity Name]                           NVARCHAR (100) NULL,
    [Int Business Unit Name]                          NVARCHAR (100) NULL,
    [Internal Portfolio Business Key]                 NVARCHAR (100) NULL,
    [Internal Portfolio Name]                         NVARCHAR (100) NULL,
    [External Portfolio Name]                         NVARCHAR (100) NULL,
    [Ext Business Unit Name]                          NVARCHAR (100) NULL,
    [Ext Legal Entity Name]                           NVARCHAR (100) NULL,
    [Index Name]                                      NVARCHAR (100) NULL,
    [Trade Currency]                                  NVARCHAR (100) NULL,
    [Transaction Info Buy Sell]                       NVARCHAR (100) NULL,
    [Cashflow Type]                                   NVARCHAR (100) NULL,
    [Side Pipeline Name]                              NVARCHAR (100) NULL,
    [Instrument Subtype Name]                         NVARCHAR (100) NULL,
    [Discounting Index Name]                          NVARCHAR (100) NULL,
    [Trade Price]                                     NVARCHAR (100) NULL,
    [Cashflow Delivery Month]                         NVARCHAR (100) NULL,
    [Trade Date]                                      NVARCHAR (100) NULL,
    [Index Contract Size]                             NVARCHAR (100) NULL,
    [Discounting Index Contract Size]                 NVARCHAR (100) NULL,
    [Trade Instrument Reference Text]                 NVARCHAR (100) NULL,
    [Unit Name (Trade Std)]                           NVARCHAR (100) NULL,
    [Leg Exercise Date]                               NVARCHAR (100) NULL,
    [Cashflow Payment Date]                           NVARCHAR (100) NULL,
    [Leg End Date]                                    NVARCHAR (100) NULL,
    [Index Group]                                     NVARCHAR (100) NULL,
    [Delivery Vessel Name]                            NVARCHAR (200) NULL,
    [Static Ticket ID]                                NVARCHAR (200) NULL,
    [Volume]                                          NVARCHAR (100) NULL,
    [PnL YtD Realised Undiscounted Original Currency] NVARCHAR (100) NULL,
    [PnL YtD Realised Discounted EUR]                 NVARCHAR (100) NULL,
    [PnL YtD Realised Undiscounted EUR]               NVARCHAR (100) NULL,
    [PnL YtD Realised Discounted GBP]                 NVARCHAR (100) NULL,
    [PnL YtD Realised Undiscounted GBP]               NVARCHAR (100) NULL,
    [PnL YtD Realised Discounted USD]                 NVARCHAR (100) NULL,
    [PnL YtD Realised Undiscounted USD]               NVARCHAR (100) NULL,
    [Unrealised Discounted EUR]                       NVARCHAR (100) NULL,
    [Unrealised Undiscounted EUR]                     NVARCHAR (100) NULL,
    [Unrealised Discounted GBP]                       NVARCHAR (100) NULL,
    [Unrealised Undiscounted GBP]                     NVARCHAR (100) NULL,
    [Unrealised Discounted Original Currency]         NVARCHAR (100) NULL,
    [Unrealised Undiscounted Original Currency]       NVARCHAR (100) NULL,
    [Unrealised Discounted USD]                       NVARCHAR (100) NULL,
    [Unrealised Undiscounted USD]                     NVARCHAR (100) NULL,
    [FileID]                                          INT            NULL
);


GO

