CREATE TABLE [dbo].[Recon_UK_Diff] (
    [InternalLegalEntity]    VARCHAR (100) NULL,
    [Desk]                   VARCHAR (50)  NULL,
    [SubDesk]                VARCHAR (200) NULL,
    [book]                   VARCHAR (255) NULL,
    [ReconGroup]             VARCHAR (40)  NULL,
    [OrderNo]                VARCHAR (50)  NULL,
    [DeliveryMonth]          VARCHAR (100) NULL,
    [DealID_Recon]           VARCHAR (100) NULL,
    [Account]                VARCHAR (20)  NULL,
    [ccy]                    VARCHAR (5)   NULL,
    [Portfolio]              VARCHAR (100) NULL,
    [PortfolioID]            VARCHAR (100) NULL,
    [CounterpartyGroup]      VARCHAR (100) NULL,
    [InstrumentType]         VARCHAR (100) NULL,
    [CashflowType]           VARCHAR (100) NULL,
    [ProjIndexGroup]         VARCHAR (100) NULL,
    [CurveName]              VARCHAR (100) NULL,
    [ExternalLegal]          VARCHAR (100) NULL,
    [ExternalBusinessUnit]   VARCHAR (100) NULL,
    [ExternalPortfolio]      VARCHAR (100) NULL,
    [DocumentNumber]         VARCHAR (20)  NULL,
    [Reference]              VARCHAR (100) NULL,
    [partner]                VARCHAR (20)  NULL,
    [TradeDate]              DATE          NULL,
    [EventDate]              DATE          NULL,
    [SAP_DocumentNumber]     VARCHAR (20)  NULL,
    [Volume_Endur]           FLOAT (53)    NULL,
    [Volume_SAP]             FLOAT (53)    NULL,
    [Volume_Adj]             FLOAT (53)    NULL,
    [UOM_Endur]              VARCHAR (20)  NULL,
    [UOM_SAP]                VARCHAR (20)  NULL,
    [realised_ccy_Endur]     FLOAT (53)    NULL,
    [realised_ccy_SAP]       FLOAT (53)    NULL,
    [realised_ccy_adj]       FLOAT (53)    NULL,
    [Deskccy]                VARCHAR (5)   NULL,
    [realised_Deskccy_Endur] FLOAT (53)    NULL,
    [realised_Deskccy_SAP]   FLOAT (53)    NULL,
    [realised_Deskccy_adj]   FLOAT (53)    NULL,
    [realised_EUR_Endur]     FLOAT (53)    NULL,
    [realised_EUR_SAP]       FLOAT (53)    NULL,
    [realised_EUR_adj]       FLOAT (53)    NULL,
    [Account_Endur]          VARCHAR (20)  NULL,
    [Account_SAP]            VARCHAR (20)  NULL,
    [Diff_Volume]            FLOAT (53)    NULL,
    [Diff_Realised_CCY]      FLOAT (53)    NULL,
    [Diff_Realised_DeskCCY]  FLOAT (53)    NULL,
    [Diff_Realised_EUR]      FLOAT (53)    NULL,
    [AbsDiff_CCY]            FLOAT (53)    NULL,
    [Identifier]             VARCHAR (255) NULL
);


GO

