CREATE TABLE [dbo].[Recon_UK_Diff_SF] (
    [InternalLegalEntity]    VARCHAR (100)  NULL,
    [Desk]                   VARCHAR (50)   NULL,
    [SubDesk]                VARCHAR (200)  NULL,
    [ReconGroup]             VARCHAR (40)   NULL,
    [OrderNo]                VARCHAR (50)   NULL,
    [DeliveryMonth]          VARCHAR (100)  NULL,
    [DealID_Recon]           VARCHAR (100)  NULL,
    [DealID]                 VARCHAR (100)  NULL,
    [Account]                VARCHAR (20)   NULL,
    [ccy]                    VARCHAR (5)    NULL,
    [Portfolio]              VARCHAR (100)  NULL,
    [Portfolio_ID]           VARCHAR (100)  NULL,
    [CounterpartyGroup]      VARCHAR (100)  NULL,
    [InstrumentType]         VARCHAR (100)  NULL,
    [CashflowType]           VARCHAR (100)  NULL,
    [ProjIndexGroup]         VARCHAR (100)  NULL,
    [CurveName]              VARCHAR (100)  NULL,
    [ExternalLegal]          VARCHAR (100)  NULL,
    [ExternalBusinessUnit]   VARCHAR (100)  NULL,
    [ExternalPortfolio]      VARCHAR (100)  NULL,
    [DocumentNumber]         VARCHAR (20)   NULL,
    [Reference]              VARCHAR (100)  NULL,
    [partner]                VARCHAR (20)   NULL,
    [TradeDate]              VARCHAR (94)   NULL,
    [EventDate]              VARCHAR (94)   NULL,
    [SAP_DocumentNumber]     VARCHAR (20)   NULL,
    [Volume_Endur]           FLOAT (53)     NULL,
    [Volume_SAP]             FLOAT (53)     NULL,
    [Volume_Adj]             FLOAT (53)     NULL,
    [UOM_Endur]              VARCHAR (20)   NULL,
    [UOM_SAP]                VARCHAR (20)   NULL,
    [realised_ccy_Endur]     FLOAT (53)     NULL,
    [realised_ccy_SAP]       FLOAT (53)     NULL,
    [realised_ccy_adj]       FLOAT (53)     NULL,
    [DeskCcy]                VARCHAR (5)    NULL,
    [realised_deskccy_endur] FLOAT (53)     NULL,
    [realised_Deskccy_SAP]   FLOAT (53)     NULL,
    [realised_deskccy_adj]   FLOAT (53)     NULL,
    [realised_EUR_Endur]     FLOAT (53)     NULL,
    [realised_EUR_SAP]       FLOAT (53)     NULL,
    [realised_EUR_adj]       FLOAT (53)     NULL,
    [Account_Endur]          VARCHAR (20)   NULL,
    [Account_SAP]            VARCHAR (20)   NULL,
    [Diff_Volume]            FLOAT (53)     NULL,
    [Diff_CCY]               FLOAT (53)     NULL,
    [Diff_DeskCCY]           FLOAT (53)     NULL,
    [Diff_EUR]               FLOAT (53)     NULL,
    [abs_diff_CCY]           FLOAT (53)     NULL,
    [PaymentDateInfo]        VARCHAR (19)   NOT NULL,
    [AccrualPostingText]     VARCHAR (8000) NULL,
    [CountryCode]            VARCHAR (40)   NULL,
    [StKZ]                   VARCHAR (20)   NULL,
    [PK_PNL]                 VARCHAR (2)    NOT NULL,
    [Account_PNL]            VARCHAR (8000) NULL,
    [PK_BS]                  VARCHAR (2)    NOT NULL,
    [Account_BS]             VARCHAR (255)  NULL,
    [UstID]                  VARCHAR (255)  NULL,
    [Material]               VARCHAR (50)   NULL,
    [MaterialDescription]    VARCHAR (255)  NULL,
    [Identifier]             VARCHAR (255)  NULL
);


GO

