CREATE TABLE [dbo].[Strolf_REALIZED_CARMEN] (
    [COB]                   DATETIME       NULL,
    [TRADE_DEAL_NUMBER]     NVARCHAR (400) NULL,
    [INS_TYPE_NAME]         NVARCHAR (400) NULL,
    [LENTITY_NAME]          NVARCHAR (400) NULL,
    [PORTFOLIO_NAME]        NVARCHAR (400) NULL,
    [EXT_LENTITY_NAME]      NVARCHAR (400) NULL,
    [TRADE_CURRENCY]        NVARCHAR (3)   NULL,
    [CASHFLOW_TYPE]         NVARCHAR (400) NULL,
    [TRADE_DATE]            DATETIME       NULL,
    [UNIT_NAME]             NVARCHAR (400) NULL,
    [CASHFLOW_PAYMENT_DATE] DATETIME       NULL,
    [INDEX_GROUP]           NVARCHAR (400) NULL,
    [VOLUME]                FLOAT (53)     NULL,
    [REALISED_EUR_UNDISC]   FLOAT (53)     NULL,
    [DELIVERY_MONTH]        DATETIME       NULL,
    [TRADE_REFERENCE_TEXT]  NVARCHAR (100) NULL
);


GO

