CREATE TABLE [dbo].[Strolf_HIST_PNL_PORT_FIN_EOM] (
    [ID]             INT            IDENTITY (1, 1) NOT NULL,
    [COB]            DATETIME       NULL,
    [PORTFOLIO_ID]   NVARCHAR (400) NULL,
    [PORTFOLIO_NAME] NVARCHAR (100) NULL,
    [PROJ_IDX]       NVARCHAR (400) NULL,
    [INDEX_NAME]     NVARCHAR (100) NULL,
    [COMMODITY_TYPE] NVARCHAR (100) NULL,
    [EXT_BUNIT_NAME] NVARCHAR (100) NULL,
    [INS_TYPE_ID]    NVARCHAR (400) NULL,
    [MONTH]          DATETIME       NULL,
    [PNL_Type]       NVARCHAR (100) NULL,
    [PNL]            FLOAT (53)     NULL,
    [CURRENCY]       NVARCHAR (3)   NULL,
    [Month_ORIG]     DATETIME       NULL,
    [INS_TYPE_NAME]  NVARCHAR (50)  NULL,
    CONSTRAINT [pk_Strolf_HIST_PNL_PORT_FIN_EOM] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO

