CREATE TABLE [dbo].[Table_FX_Rates_Timeseries_ECB_raw] (
    [COB]       DATE          NULL,
    [USD]       NVARCHAR (50) NULL,
    [JPY]       NVARCHAR (50) NULL,
    [BGN]       NVARCHAR (50) NULL,
    [CYP]       NVARCHAR (50) NULL,
    [CZK]       NVARCHAR (50) NULL,
    [DKK]       NVARCHAR (50) NULL,
    [EEK]       NVARCHAR (50) NULL,
    [GBP]       NVARCHAR (50) NULL,
    [HUF]       NVARCHAR (50) NULL,
    [LTL]       NVARCHAR (50) NULL,
    [LVL]       NVARCHAR (50) NULL,
    [MTL]       NVARCHAR (50) NULL,
    [PLN]       NVARCHAR (50) NULL,
    [ROL]       NVARCHAR (50) NULL,
    [RON]       NVARCHAR (50) NULL,
    [SEK]       NVARCHAR (50) NULL,
    [SIT]       NVARCHAR (50) NULL,
    [SKK]       NVARCHAR (50) NULL,
    [CHF]       NVARCHAR (50) NULL,
    [ISK]       NVARCHAR (50) NULL,
    [NOK]       NVARCHAR (50) NULL,
    [HRK]       NVARCHAR (50) NULL,
    [RUB]       NVARCHAR (50) NULL,
    [TRL]       NVARCHAR (50) NULL,
    [TRY]       NVARCHAR (50) NULL,
    [AUD]       NVARCHAR (50) NULL,
    [BRL]       NVARCHAR (50) NULL,
    [CAD]       NVARCHAR (50) NULL,
    [CNY]       NVARCHAR (50) NULL,
    [HKD]       NVARCHAR (50) NULL,
    [IDR]       NVARCHAR (50) NULL,
    [ILS]       NVARCHAR (50) NULL,
    [INR]       NVARCHAR (50) NULL,
    [KRW]       NVARCHAR (50) NULL,
    [MXN]       NVARCHAR (50) NULL,
    [MYR]       NVARCHAR (50) NULL,
    [NZD]       NVARCHAR (50) NULL,
    [PHP]       NVARCHAR (50) NULL,
    [SGD]       NVARCHAR (50) NULL,
    [THB]       NVARCHAR (50) NULL,
    [ZAR]       NVARCHAR (50) NULL,
    [Column_43] NVARCHAR (50) NULL
);


GO

