CREATE TABLE [dbo].[table_HA_Measurement_report_detailed] (
    [cob]                 DATE           NULL,
    [Valuation_DATE]      DATE           NULL,
    [Sub]                 NVARCHAR (100) NULL,
    [Strategy]            NVARCHAR (100) NULL,
    [Book]                NVARCHAR (100) NULL,
    [DER_Item]            NVARCHAR (100) NULL,
    [Deal_REF_ID]         INT            NULL,
    [Deal_ID]             INT            NULL,
    [Rel_ID]              INT            NULL,
    [DeDesig_Rel_ID]      INT            NULL,
    [Rel_TYPE]            NVARCHAR (100) NULL,
    [Counterparty]        NVARCHAR (100) NULL,
    [Deal_DATE]           DATE           NULL,
    [Rel_Eff_DATE]        DATE           NULL,
    [DeDesig_DATE]        DATE           NULL,
    [Term]                DATE           NULL,
    [Perc]                FLOAT (53)     NULL,
    [Total_Volume]        FLOAT (53)     NULL,
    [Volume_Used]         FLOAT (53)     NULL,
    [UOM]                 NVARCHAR (100) NULL,
    [Index_Name]          NVARCHAR (100) NULL,
    [DF]                  FLOAT (53)     NULL,
    [Deal_Price]          FLOAT (53)     NULL,
    [Market_Price]        FLOAT (53)     NULL,
    [Inception_Price]     FLOAT (53)     NULL,
    [CCY]                 NVARCHAR (3)   NULL,
    [Cum_FV]              FLOAT (53)     NULL,
    [Cum_INT_FV]          FLOAT (53)     NULL,
    [Incpt_FV]            FLOAT (53)     NULL,
    [Incpt_INT_FV]        FLOAT (53)     NULL,
    [Cum_Hedge_FV]        FLOAT (53)     NULL,
    [Hedge_AOCI_Ratio]    FLOAT (53)     NULL,
    [Dollar_Offset_Ratio] FLOAT (53)     NULL,
    [Test_result]         NVARCHAR (100) NULL,
    [AOCI]                FLOAT (53)     NULL,
    [PNL]                 FLOAT (53)     NULL,
    [AOCI_Released]       FLOAT (53)     NULL,
    [PNL_Settled]         FLOAT (53)     NULL,
    [FileID]              INT            NULL,
    [LastUpdate]          DATETIME       CONSTRAINT [DF_table_Measurement_report_detailed_LastUpdate] DEFAULT (getdate()) NULL
);


GO

