CREATE TABLE [dbo].[table_FTvsROCK_ROCKData_tmp] (
    [COB]                     NVARCHAR (200) NULL,
    [DESK_NAME]               NVARCHAR (200) NULL,
    [TRADE_DEAL_NUMBER]       NVARCHAR (200) NULL,
    [PORTFOLIO_NAME]          NVARCHAR (200) NULL,
    [INSTRUMENT_TYPE_NAME]    NVARCHAR (200) NULL,
    [CASHFLOW_MONTH]          NVARCHAR (200) NULL,
    [PDC_END_DATE]            NVARCHAR (200) NULL,
    [EXTERNAL_PORTFOLIO_NAME] NVARCHAR (200) NULL,
    [UNREAL_DISC_PH_BL_CCY]   NVARCHAR (200) NULL,
    [REAL_DISC_PH_BL_CCY]     NVARCHAR (200) NULL
);


GO

