CREATE TABLE [dbo].[table_unrealised_data_comparison_tmp] (
    [DataSource]                                 VARCHAR (3)   NOT NULL,
    [COB]                                        DATE          NULL,
    [Desk_name]                                  VARCHAR (100) NULL,
    [Subdesk]                                    VARCHAR (255) NULL,
    [RevRec_SubDesk]                             VARCHAR (100) NULL,
    [Deal_Number]                                VARCHAR (50)  NULL,
    [Trade_Date]                                 DATE          NULL,
    [Term_End]                                   DATE          NULL,
    [Accounting_Treatment]                       VARCHAR (255) NULL,
    [Internal_Legal_Entity]                      VARCHAR (255) NULL,
    [Internal_Portfolio]                         VARCHAR (100) NULL,
    [Counterparty_Group]                         VARCHAR (100) NULL,
    [Instrument_Type]                            VARCHAR (100) NULL,
    [Projection_Index_Group]                     VARCHAR (100) NULL,
    [Projection_Index_Name]                      VARCHAR (100) NULL,
    [Product_Name]                               VARCHAR (100) NULL,
    [External_Business_Unit]                     VARCHAR (100) NULL,
    [External_Legal_Entity]                      VARCHAR (100) NULL,
    [External_Portfolio]                         VARCHAR (100) NULL,
    [Unit_of_Measure]                            VARCHAR (100) NULL,
    [Desk_CCY]                                   VARCHAR (3)   NULL,
    [Cashflow_CCY]                               VARCHAR (10)  NULL,
    [Volume]                                     FLOAT (53)    NULL,
    [Volume_Avaliable]                           FLOAT (53)    NULL,
    [Volume_Used]                                FLOAT (53)    NULL,
    [Unrealised_Discounted_BU_CCY]               FLOAT (53)    NULL,
    [Unrealised_Discounted_CF_CCY]               FLOAT (53)    NULL,
    [Realised_Discounted_BU_CCY]                 FLOAT (53)    NULL,
    [Realised_Discounted_CF_CCY]                 FLOAT (53)    NULL,
    [Total_Discounted_BU_CCY]                    FLOAT (53)    NULL,
    [Total_Discounted_CF_CCY]                    FLOAT (53)    NULL,
    [Total_Accounting_Discounted_BU_CCY]         FLOAT (53)    NULL,
    [Total_Accounting_Discounted_CF_CCY]         FLOAT (53)    NULL,
    [Total_Accounting_Discounted_CF_CCY_SAP_EUR] FLOAT (53)    NULL,
    [PNL_BU_CCY]                                 FLOAT (53)    NULL,
    [PNL_CF_CCY]                                 FLOAT (53)    NULL,
    [OCI_BU_CCY]                                 FLOAT (53)    NULL,
    [OCI_CF_CCY]                                 FLOAT (53)    NULL,
    [NOR_BU_CCY]                                 FLOAT (53)    NULL,
    [NOR_CF_CCY]                                 FLOAT (53)    NULL,
    [OU_BU_CCY]                                  FLOAT (53)    NULL,
    [OU_CF_CCY]                                  FLOAT (53)    NULL
);


GO

