CREATE TABLE [dbo].[table_Test_CAO_US_Juraj_Versus_Trd] (
    [COB]                                      DATE           NULL,
    [DeskName]                                 NVARCHAR (200) NULL,
    [TradeDealNumber]                          NVARCHAR (20)  NULL,
    [InternalPortfolio]                        NVARCHAR (100) NULL,
    [InstrumentType]                           NVARCHAR (100) NULL,
    [CashflowDeliveryMonth]                    DATE           NULL,
    [LegEndDate]                               DATE           NULL,
    [ExternalPortfolio]                        NVARCHAR (100) NULL,
    [UnrealisedDiscounted]                     FLOAT (53)     NULL,
    [RealisedDiscounted]                       FLOAT (53)     NULL,
    [FileID]                                   INT            NULL,
    [Deal Type]                                VARCHAR (10)   NULL,
    [Reference ID]                             VARCHAR (50)   NULL,
    [Tran Number]                              VARCHAR (50)   NULL,
    [Offset Tran Num]                          VARCHAR (50)   NULL,
    [Trade Date]                               DATETIME       NULL,
    [Term_Start]                               DATETIME       NULL,
    [Term_End]                                 DATETIME       NULL,
    [Trader]                                   VARCHAR (50)   NULL,
    [Trader ID]                                VARCHAR (50)   NULL,
    [Portfolio Name]                           VARCHAR (50)   NULL,
    [Portfolio ID]                             VARCHAR (50)   NULL,
    [Counterparty]                             VARCHAR (100)  NULL,
    [Counterparty ID]                          VARCHAR (50)   NULL,
    [Counterparty Group]                       VARCHAR (50)   NULL,
    [Deal Volume]                              FLOAT (53)     NULL,
    [Buy/Sell Flag]                            VARCHAR (1)    NULL,
    [Expiration Date]                          DATETIME       NULL,
    [Deal Price]                               FLOAT (53)     NULL,
    [Trade Status]                             VARCHAR (10)   NULL,
    [Settlement Date]                          DATETIME       NULL,
    [Price Curve Name]                         VARCHAR (100)  NULL,
    [Price Curve ID]                           VARCHAR (100)  NULL,
    [Price Curve Currency]                     VARCHAR (50)   NULL,
    [Price Curve UOM]                          VARCHAR (50)   NULL,
    [Commodity Name]                           VARCHAR (50)   NULL,
    [Company Code]                             VARCHAR (100)  NULL,
    [Contract Detail]                          VARCHAR (50)   NULL,
    [Deal Currency]                            VARCHAR (50)   NULL,
    [Param Seq Num]                            INT            NULL,
    [Profile Seq Num]                          INT            NULL,
    [Instrument Type]                          VARCHAR (50)   NULL,
    [Instrument Sub-Type]                      VARCHAR (50)   NULL,
    [Fixed/Float Flag]                         VARCHAR (1)    NULL,
    [Buy/Sell Flag deal detail/delivery month] VARCHAR (1)    NULL,
    [Volume Frequency]                         VARCHAR (1)    NULL,
    [Unit of Measure]                          VARCHAR (50)   NULL,
    [Price Currency ID]                        VARCHAR (50)   NULL,
    [Broker Name]                              VARCHAR (50)   NULL,
    [Legal Entity]                             VARCHAR (50)   NULL,
    [IntBunit]                                 VARCHAR (50)   NULL,
    [Ext Legal]                                VARCHAR (50)   NULL,
    [Ext Pfolio]                               VARCHAR (50)   NULL,
    [Option Type]                              VARCHAR (4)    NULL,
    [Option Strike]                            FLOAT (53)     NULL,
    [Option Premium]                           FLOAT (53)     NULL,
    [Premium Settlement Date]                  DATETIME       NULL,
    [Commentary]                               VARCHAR (250)  NULL,
    [Product]                                  VARCHAR (50)   NULL,
    [Unit Of Measure2]                         VARCHAR (50)   NULL
);


GO

