CREATE TABLE [dbo].[table_Day1ProfitLoss_TRADE] (
    [Deal_Type]               NVARCHAR (150) NULL,
    [Reference_ID]            NVARCHAR (150) NULL,
    [Tran_Number]             NVARCHAR (150) NULL,
    [Offset_Tran_Number]      NVARCHAR (150) NULL,
    [Trade_Date]              DATETIME       NULL,
    [Term_Start]              DATETIME       NULL,
    [Term_End]                DATETIME       NULL,
    [Trader_Name]             NVARCHAR (150) NULL,
    [Trader_ID]               NVARCHAR (150) NULL,
    [Portfolio_Name]          NVARCHAR (150) NULL,
    [Portfolio_ID]            NVARCHAR (150) NULL,
    [Counterparty]            NVARCHAR (150) NULL,
    [Counterparty_ID]         INT            NULL,
    [Counterparty_Group]      NVARCHAR (150) NULL,
    [Deal_Volume]             FLOAT (53)     NULL,
    [BuySell_Flag]            NVARCHAR (150) NULL,
    [Expiration_Date]         DATETIME       NULL,
    [Deal_Price]              FLOAT (53)     NULL,
    [Trade_Status]            NVARCHAR (150) NULL,
    [Settlement_Date]         DATETIME       NULL,
    [Price_Curve_Name]        NVARCHAR (150) NULL,
    [Price_Curve_ID]          NVARCHAR (150) NULL,
    [Price_Curve_CCY]         NVARCHAR (150) NULL,
    [Price_Curve_UOM]         NVARCHAR (150) NULL,
    [Commodity_Name]          NVARCHAR (150) NULL,
    [Company_Code]            NVARCHAR (150) NULL,
    [Contract_Detail]         NVARCHAR (150) NULL,
    [Deal_Currency]           NVARCHAR (150) NULL,
    [Param_Seq_Num]           INT            NULL,
    [Profile_Seq_Num]         INT            NULL,
    [Instrument_Type]         NVARCHAR (150) NULL,
    [Instrument_SubType]      NVARCHAR (150) NULL,
    [fix_float]               NVARCHAR (150) NULL,
    [pay_receive]             NVARCHAR (150) NULL,
    [Volume_Frequency]        NVARCHAR (150) NULL,
    [unit_name]               NVARCHAR (150) NULL,
    [Price_Currency_ID]       NVARCHAR (150) NULL,
    [Broker_Name]             NVARCHAR (150) NULL,
    [Legal_Entity]            NVARCHAR (150) NULL,
    [Internal_BU]             NVARCHAR (150) NULL,
    [External_Legal_entity]   NVARCHAR (150) NULL,
    [External_portfolio]      NVARCHAR (150) NULL,
    [Option_Type]             NVARCHAR (150) NULL,
    [Option_Strike]           FLOAT (53)     NULL,
    [Option_Premium]          FLOAT (53)     NULL,
    [Premium_Settlement_Date] DATETIME       NULL,
    [Commentary]              NVARCHAR (150) NULL,
    [Product]                 NVARCHAR (150) NULL,
    [unit_of_measure]         NVARCHAR (150) NULL
);


GO

