CREATE TABLE [dbo].[table_deferral_Clearer_DealData_kaskading] (
    [ID]                   INT            NOT NULL,
    [ReportDate]           DATE           NOT NULL,
    [DealNumber]           NVARCHAR (200) NULL,
    [AccountName]          NVARCHAR (200) NULL,
    [InternalPortfolio]    NVARCHAR (200) NULL,
    [ExternalBusinessUnit] NVARCHAR (200) NULL,
    [ContractName]         NVARCHAR (200) NULL,
    [ContractSize]         FLOAT (53)     NULL,
    [BrokerName]           NVARCHAR (200) NULL,
    [TradeDate]            DATE           NULL,
    [StartDate]            DATE           NULL,
    [EndDate]              DATE           NULL,
    [ProjectionIndex1]     NVARCHAR (200) NULL,
    [ProjectionIndex2]     NVARCHAR (200) NULL,
    [Toolset]              NVARCHAR (200) NULL,
    [Position]             FLOAT (53)     NULL,
    [CCY]                  NVARCHAR (3)   NULL,
    [TradePrice]           FLOAT (53)     NULL,
    [StrikePrice]          FLOAT (53)     NULL,
    [Premium]              FLOAT (53)     NULL,
    [CallPut]              NVARCHAR (20)  NULL,
    [FeeType]              NVARCHAR (200) NULL,
    [FeeRate]              FLOAT (53)     NULL,
    [TotalFee]             FLOAT (53)     NULL,
    [AdjustedTotalFee]     FLOAT (53)     NULL,
    [ClearerID]            INT            NOT NULL,
    [ClearerType]          NVARCHAR (200) NOT NULL,
    [Source]               NVARCHAR (200) NULL,
    [LastImport]           DATETIME       NOT NULL,
    [Type]                 VARCHAR (255)  NULL,
    [1]                    FLOAT (53)     NULL,
    [2]                    FLOAT (53)     NULL,
    [3]                    FLOAT (53)     NULL,
    [4]                    FLOAT (53)     NULL,
    [5]                    FLOAT (53)     NULL,
    [6]                    FLOAT (53)     NULL,
    [7]                    FLOAT (53)     NULL,
    [8]                    FLOAT (53)     NULL,
    [9]                    FLOAT (53)     NULL,
    [10]                   FLOAT (53)     NULL,
    [11]                   FLOAT (53)     NULL,
    [12]                   FLOAT (53)     NULL
);


GO

