CREATE TABLE [dbo].[table_Test_CAO_US_Endur_File] (
    [Deal #]              VARCHAR (10) NULL,
    [Tran #]              VARCHAR (10) NULL,
    [Group #]             VARCHAR (10) NULL,
    [Status]              VARCHAR (11) NULL,
    [Toolset]             VARCHAR (11) NULL,
    [Ins Type]            VARCHAR (22) NULL,
    [Ins #]               VARCHAR (10) NULL,
    [Tran Type]           VARCHAR (8)  NULL,
    [Asset Type]          VARCHAR (8)  NULL,
    [CCY]                 VARCHAR (4)  NULL,
    [Reference]           VARCHAR (38) NULL,
    [Buy/Sell]            VARCHAR (5)  NULL,
    [Price]               FLOAT (53)   NULL,
    [Position]            FLOAT (53)   NULL,
    [Trade Date]          DATETIME     NULL,
    [Input Date]          DATETIME     NULL,
    [Settle Date]         DATETIME     NULL,
    [Start Date]          DATETIME     NULL,
    [Maturity Date]       DATETIME     NULL,
    [Int Bunit]           VARCHAR (31) NULL,
    [Int Lentity]         VARCHAR (13) NULL,
    [Int Pfolio]          VARCHAR (31) NULL,
    [Int Contact]         VARCHAR (22) NULL,
    [Ext Bunit]           VARCHAR (43) NULL,
    [Ext Lentity]         VARCHAR (38) NULL,
    [Ext pfolio]          VARCHAR (38) NULL,
    [Ext Contact]         VARCHAR (20) NULL,
    [Book]                VARCHAR (36) NULL,
    [Rate]                VARCHAR (1)  NULL,
    [CFlow Type]          VARCHAR (8)  NULL,
    [Version]             VARCHAR (5)  NULL,
    [Proceeds]            FLOAT (53)   NULL,
    [MValue]              FLOAT (53)   NULL,
    [Personnel ID]        VARCHAR (28) NULL,
    [Last Update]         DATETIME     NULL,
    [Ins Sub-type]        VARCHAR (18) NULL,
    [Broker ID]           VARCHAR (30) NULL,
    [Perpetual Pos Date]  DATETIME     NULL,
    [Trade Time]          DATETIME     NULL,
    [Ins Class]           VARCHAR (7)  NULL,
    [Unit]                VARCHAR (10) NULL,
    [Offset Tran No.]     VARCHAR (10) NULL,
    [Offset Tran Type]    VARCHAR (19) NULL,
    [Deal Index Group]    VARCHAR (13) NULL,
    [Deal Index SubGroup] VARCHAR (5)  NULL,
    [Ins Reference]       VARCHAR (38) NULL
);


GO

