CREATE TABLE [dbo].[table_unrealised_order_mufti_with_accounts] (
    [Desk]                   VARCHAR (50)  NULL,
    [Subdesk]                VARCHAR (255) NULL,
    [SubDeskCCY]             VARCHAR (3)   NULL,
    [AsofDate]               DATETIME      NULL,
    [Sub ID]                 INT           NULL,
    [Subsidiary]             VARCHAR (255) NULL,
    [Strategy]               VARCHAR (255) NULL,
    [Book]                   VARCHAR (255) NULL,
    [AccountingTreatment]    VARCHAR (255) NULL,
    [InternalPortfolio]      VARCHAR (50)  NULL,
    [ExternalBusinessUnit]   VARCHAR (50)  NULL,
    [ExtLegalEntity]         VARCHAR (50)  NULL,
    [ExtPortfolio]           VARCHAR (50)  NULL,
    [CounterpartyGroup]      VARCHAR (50)  NULL,
    [InstrumentType]         VARCHAR (50)  NULL,
    [ProjIndexGroup]         VARCHAR (50)  NULL,
    [CurveName]              VARCHAR (50)  NULL,
    [Product]                VARCHAR (50)  NULL,
    [ReferenceID]            VARCHAR (50)  NULL,
    [TradeDate]              DATETIME      NULL,
    [TermEnd]                DATETIME      NULL,
    [Total_MTM]              FLOAT (53)    NULL,
    [PNL]                    FLOAT (53)    NULL,
    [OCI]                    FLOAT (53)    NULL,
    [OU]                     FLOAT (53)    NULL,
    [NOR]                    FLOAT (53)    NULL,
    [UOM]                    VARCHAR (50)  NULL,
    [Volume]                 FLOAT (53)    NULL,
    [VolumeAvailable]        FLOAT (53)    NULL,
    [VolumeUsed]             FLOAT (53)    NULL,
    [DeskCCY]                VARCHAR (3)   NULL,
    [Total_MTM_DeskCCY]      FLOAT (53)    NULL,
    [PNL_DeskCCY]            FLOAT (53)    NULL,
    [OCI_DeskCCY]            FLOAT (53)    NULL,
    [OU_DeskCCY]             FLOAT (53)    NULL,
    [NOR_DeskCCY]            FLOAT (53)    NULL,
    [AsOfDate_a]             SMALLDATETIME NULL,
    [Subsidiary_a]           VARCHAR (255) NULL,
    [Strategy_a]             VARCHAR (255) NULL,
    [Book_a]                 VARCHAR (255) NULL,
    [InternalPortfolio_a]    VARCHAR (255) NULL,
    [CounterpartyGroup_a]    VARCHAR (255) NULL,
    [InstrumentType_a]       VARCHAR (255) NULL,
    [ProjectionIndexGroup_a] VARCHAR (255) NULL,
    [AccountingTreatment_a]  VARCHAR (255) NULL,
    [HedgeSTAsset_a]         VARCHAR (255) NULL,
    [HedgeLTAsset_a]         VARCHAR (255) NULL,
    [HedgeSTLiability_a]     VARCHAR (255) NULL,
    [HedgeLTLiability_a]     VARCHAR (255) NULL,
    [UnhedgedSTAsset_a]      VARCHAR (255) NULL,
    [UnhedgedLTAsset_a]      VARCHAR (255) NULL,
    [UnhedgedSTLiability_a]  VARCHAR (255) NULL,
    [UnhedgedLTLiability_a]  VARCHAR (255) NULL,
    [AOCI_Hedge Reserve_a]   VARCHAR (255) NULL,
    [UnrealizedEarnings_a]   VARCHAR (255) NULL,
    [PortfolioID_a]          VARCHAR (255) NULL,
    [TimeStamp_a]            DATETIME      NULL,
    [User_a]                 VARCHAR (50)  NULL
);


GO

