CREATE TABLE [dbo].[table_REALISED_Rawdata] (
    [COB]                                             DATE           NULL,
    [Trade Deal Number]                               NVARCHAR (200) NULL,
    [Trade Reference Text]                            NVARCHAR (400) NULL,
    [Transaction Info Status]                         NVARCHAR (200) NULL,
    [Instrument Toolset Name]                         NVARCHAR (200) NULL,
    [Instrument Type Name]                            NVARCHAR (200) NULL,
    [Int Legal Entity Name]                           NVARCHAR (200) NULL,
    [Int Business Unit Name]                          NVARCHAR (200) NULL,
    [Internal Portfolio Business Key]                 NVARCHAR (200) NULL,
    [Internal Portfolio Name]                         NVARCHAR (200) NULL,
    [External Portfolio Name]                         NVARCHAR (200) NULL,
    [Ext Business Unit Name]                          NVARCHAR (200) NULL,
    [Ext Legal Entity Name]                           NVARCHAR (200) NULL,
    [Index Name]                                      NVARCHAR (200) NULL,
    [Trade Currency]                                  NVARCHAR (200) NULL,
    [Transaction Info Buy Sell]                       NVARCHAR (200) NULL,
    [Cashflow Type]                                   NVARCHAR (200) NULL,
    [Side Pipeline Name]                              NVARCHAR (200) NULL,
    [Instrument Subtype Name]                         NVARCHAR (200) NULL,
    [Discounting Index Name]                          NVARCHAR (200) NULL,
    [Trade Price]                                     FLOAT (53)     NULL,
    [Cashflow Delivery Month]                         DATETIME       NULL,
    [Trade Date]                                      DATETIME       NULL,
    [Index Contract Size]                             FLOAT (53)     NULL,
    [Discounting Index Contract Size]                 NVARCHAR (200) NULL,
    [Trade Instrument Reference Text]                 NVARCHAR (200) NULL,
    [Unit Name (Trade Std)]                           NVARCHAR (200) NULL,
    [Leg Exercise Date]                               DATETIME       NULL,
    [Cashflow Payment Date]                           DATETIME       NULL,
    [Leg End Date]                                    DATETIME       NULL,
    [Index Group]                                     NVARCHAR (200) NULL,
    [Delivery Vessel Name]                            NVARCHAR (200) NULL,
    [Static Ticket ID]                                NVARCHAR (200) NULL,
    [SETTLEMENT_TYPE_NAME]                            NVARCHAR (200) NULL,
    [Volume]                                          FLOAT (53)     NULL,
    [PnL YtD Realised Undiscounted Original Currency] FLOAT (53)     NULL,
    [PnL YtD Realised Discounted EUR]                 FLOAT (53)     NULL,
    [PnL YtD Realised Undiscounted EUR]               FLOAT (53)     NULL,
    [PnL YtD Realised Discounted GBP]                 FLOAT (53)     NULL,
    [PnL YtD Realised Undiscounted GBP]               FLOAT (53)     NULL,
    [PnL YtD Realised Discounted USD]                 FLOAT (53)     NULL,
    [PnL YtD Realised Undiscounted USD]               FLOAT (53)     NULL,
    [Unrealised Discounted EUR]                       FLOAT (53)     NULL,
    [Unrealised Undiscounted EUR]                     FLOAT (53)     NULL,
    [Unrealised Discounted GBP]                       FLOAT (53)     NULL,
    [Unrealised Undiscounted GBP]                     FLOAT (53)     NULL,
    [Unrealised Discounted Original Currency]         FLOAT (53)     NULL,
    [Unrealised Undiscounted Original Currency]       FLOAT (53)     NULL,
    [Unrealised Discounted USD]                       FLOAT (53)     NULL,
    [Unrealised Undiscounted USD]                     FLOAT (53)     NULL,
    [DESK_NAME]                                       NVARCHAR (200) NULL,
    [INTERMEDIATE1_NAME]                              NVARCHAR (200) NULL,
    [BOOK_NAME]                                       NVARCHAR (200) NULL,
    [INTERMEDIATE1_CURRENCY]                          NVARCHAR (100) NULL,
    [REAL_DISC_CASHFLOW_CCY_YTD]                      FLOAT (53)     NULL,
    [REAL_UNDISC_PH_IM1_CCY_YTD]                      FLOAT (53)     NULL,
    [REAL_DISC_PH_IM1_CCY_YTD]                        FLOAT (53)     NULL,
    [UNREAL_UNDISC_PH_IM1_CCY]                        FLOAT (53)     NULL,
    [UNREAL_DISC_PH_IM1_CCY]                          FLOAT (53)     NULL,
    [SOURCE_OF_ROW]                                   NVARCHAR (200) NULL,
    [FileID]                                          INT            NULL
);


GO

