CREATE TABLE [dbo].[table_RISK_ADJUSTMENTS] (
    [ID]                               INT            IDENTITY (1, 1) NOT NULL,
    [COB]                              DATETIME       NULL,
    [BUSINESS_LINE_NAME]               VARCHAR (50)   NULL,
    [DESK_NAME]                        VARCHAR (50)   NULL,
    [INTERMEDIATE1_NAME]               NVARCHAR (50)  NULL,
    [INTERMEDIATE2_NAME]               NVARCHAR (50)  NULL,
    [INTERMEDIATE3_NAME]               NVARCHAR (50)  NULL,
    [INTERMEDIATE4_NAME]               NVARCHAR (50)  NULL,
    [BOOK_NAME]                        NVARCHAR (50)  NULL,
    [PORTFOLIO_NAME]                   VARCHAR (60)   NULL,
    [CATEGORY_NAME]                    VARCHAR (50)   NULL,
    [SUB_CATEGORY_NAME]                VARCHAR (50)   NULL,
    [ADJUSTMENT_ID]                    NVARCHAR (50)  NULL,
    [USER_COMMENT]                     VARCHAR (1500) NULL,
    [UserID]                           VARCHAR (50)   NULL,
    [CASHFLOW_CURRENCY]                NVARCHAR (3)   NULL,
    [VALID_FROM]                       NVARCHAR (200) NULL,
    [VALID_TO]                         NVARCHAR (200) NULL,
    [PAYMENT_DATE]                     NVARCHAR (50)  NULL,
    [BUSINESS_LINE_CURRENCY]           NVARCHAR (10)  NULL,
    [INTERMEDIATE1_CURRENCY]           NVARCHAR (10)  NULL,
    [Realised Discounted EUR]          FLOAT (53)     NULL,
    [Realised Discounted EUR - EOLY]   FLOAT (53)     NULL,
    [Unrealised Discounted EUR]        FLOAT (53)     NULL,
    [Unrealised Discounted EUR - EOLY] FLOAT (53)     NULL,
    [Realised Discounted USD]          FLOAT (53)     NULL,
    [Realised Discounted USD - EOLY]   FLOAT (53)     NULL,
    [Unrealised Discounted USD]        FLOAT (53)     NULL,
    [Unrealised Discounted USD - EOLY] FLOAT (53)     NULL,
    [Realised Discounted GBP]          FLOAT (53)     NULL,
    [Realised Discounted GBP - EOLY]   FLOAT (53)     NULL,
    [Unrealised Discounted GBP]        FLOAT (53)     NULL,
    [Unrealised Discounted GBP EOLY]   FLOAT (53)     NULL,
    [REAL_DISC_PH_IM1_CCY]             FLOAT (53)     NULL,
    [UNREAL_DISC_PH_IM1_CCY]           FLOAT (53)     NULL,
    [REAL_DISC_PH_IM1_CCY_LGBY]        FLOAT (53)     NULL,
    [UNREAL_DISC_PH_IM1_CCY_LGBY]      FLOAT (53)     NULL,
    [UNREAL_DISC_BL_CCY]               FLOAT (53)     NULL,
    [UNREAL_DISC_PH_BL_CCY]            FLOAT (53)     NULL,
    [UNREAL_DISC_BL_CCY_LGBY]          FLOAT (53)     NULL,
    [UNREAL_DISC_PH_BL_CCY_LGBY]       FLOAT (53)     NULL,
    [REAL_DISC_PH_BL_CCY_YTD]          FLOAT (53)     NULL,
    [REAL_DISC_PH_IM1_CCY_YTD]         FLOAT (53)     NULL,
    [TOTAL_VALUE_PH_IM1_CCY_YTD]       FLOAT (53)     NULL,
    [TOTAL_VALUE_PH_BL_CCY_YTD]        FLOAT (53)     NULL,
    [REAL_UNDISC_CASHFLOW_CCY_YTD]     FLOAT (53)     NULL,
    [REAL_UNDISC_CASHFLOW_CCY]         FLOAT (53)     NULL,
    [UNREAL_DISC_CASHFLOW_CCY]         FLOAT (53)     NULL,
    [UNREAL_DISC_CASHFLOW_CCY_YTD]     FLOAT (53)     NULL,
    [REAL_DISC_PH_BL_CCY_MTD]          FLOAT (53)     NULL,
    [UNREAL_DISC_PH_BL_CCY_MTD]        FLOAT (53)     NULL,
    [FileId]                           INT            NULL,
    [LastUpdate]                       DATETIME       CONSTRAINT [DF_table_ROCK_RiskAdjustments_LastUpdate] DEFAULT (getdate()) NULL
);


GO

