CREATE TABLE [dbo].[temp_BeckyDouble_3038] (
    [Trade Deal Number]               VARCHAR (100) NULL,
    [Trade Reference Text]            VARCHAR (400) NULL,
    [Transaction Info Status]         VARCHAR (100) NULL,
    [Instrument Toolset Name]         VARCHAR (100) NULL,
    [Instrument Type Name]            VARCHAR (100) NULL,
    [Int Legal Entity Name]           VARCHAR (100) NULL,
    [Int Business Unit Name]          VARCHAR (100) NULL,
    [Internal Portfolio Business Key] VARCHAR (100) NULL,
    [Internal Portfolio Name]         VARCHAR (100) NULL,
    [External Portfolio Name]         VARCHAR (100) NULL,
    [Ext Business Unit Name]          VARCHAR (100) NULL,
    [Ext Legal Entity Name]           VARCHAR (100) NULL,
    [Index Name]                      VARCHAR (100) NULL,
    [Trade Currency]                  VARCHAR (100) NULL,
    [Transaction Info Buy Sell]       VARCHAR (100) NULL,
    [Cashflow Type]                   VARCHAR (100) NULL,
    [Side Pipeline Name]              VARCHAR (100) NULL,
    [Instrument Subtype Name]         VARCHAR (100) NULL,
    [Discounting Index Name]          VARCHAR (100) NULL,
    [Trade Price]                     FLOAT (53)    NULL,
    [Document Number]                 VARCHAR (100) NULL,
    [Cashflow Delivery Month]         VARCHAR (100) NULL,
    [Trade Date]                      DATETIME      NULL,
    [Index Contract Size]             FLOAT (53)    NULL,
    [Discounting Index Contract Size] VARCHAR (100) NULL,
    [Trade Instrument Reference Text] VARCHAR (100) NULL,
    [Unit Name (Trade Std)]           VARCHAR (100) NULL,
    [Leg Exercise Date]               DATETIME      NULL,
    [Cashflow Payment Date]           DATETIME      NULL,
    [Leg End Date]                    DATETIME      NULL,
    [Index Group]                     VARCHAR (100) NULL,
    [Delivery Vessel Name]            VARCHAR (50)  NULL,
    [Static Ticket ID]                VARCHAR (50)  NULL,
    [Metrics]                         VARCHAR (100) NULL,
    [volume]                          FLOAT (53)    NULL,
    [Realised_OrigCCY_Undisc]         FLOAT (53)    NULL,
    [Realised_EUR_Undisc]             FLOAT (53)    NULL,
    [Realised_EUR_Disc]               FLOAT (53)    NULL,
    [Realised_GBP_Undisc]             FLOAT (53)    NULL,
    [Realised_GBP_Disc]               FLOAT (53)    NULL,
    [Realised_USD_Undisc]             FLOAT (53)    NULL,
    [Realised_USD_Disc]               FLOAT (53)    NULL,
    [Delivery Month]                  VARCHAR (100) NULL,
    [FileID]                          INT           NULL
);


GO

