CREATE TABLE [dbo].[Temp_table_Test_CAO_US_Trade_File] (
    [Deal Type]                                VARCHAR (10)  NULL,
    [Reference ID]                             VARCHAR (50)  NULL,
    [Tran Number]                              VARCHAR (50)  NULL,
    [Offset Tran Num]                          VARCHAR (50)  NULL,
    [Trade Date]                               VARCHAR (10)  NULL,
    [Term_Start]                               VARCHAR (10)  NULL,
    [Term_End]                                 VARCHAR (10)  NULL,
    [Trader]                                   VARCHAR (50)  NULL,
    [Trader ID]                                VARCHAR (50)  NULL,
    [Portfolio Name]                           VARCHAR (50)  NULL,
    [Portfolio ID]                             VARCHAR (50)  NULL,
    [Counterparty]                             VARCHAR (100) NULL,
    [Counterparty ID]                          VARCHAR (50)  NULL,
    [Counterparty Group]                       VARCHAR (50)  NULL,
    [Deal Volume]                              VARCHAR (58)  NULL,
    [Buy/Sell Flag]                            VARCHAR (1)   NULL,
    [Expiration Date]                          VARCHAR (10)  NULL,
    [Deal Price]                               VARCHAR (58)  NULL,
    [Trade Status]                             VARCHAR (10)  NULL,
    [Settlement Date]                          VARCHAR (10)  NULL,
    [Price Curve Name]                         VARCHAR (100) NULL,
    [Price Curve ID]                           VARCHAR (100) NULL,
    [Price Curve Currency]                     VARCHAR (50)  NULL,
    [Price Curve UOM]                          VARCHAR (50)  NULL,
    [Commodity Name]                           VARCHAR (50)  NULL,
    [Company Code]                             VARCHAR (100) NULL,
    [Contract Detail]                          VARCHAR (50)  NULL,
    [Deal Currency]                            VARCHAR (50)  NULL,
    [Param Seq Num]                            VARCHAR (8)   NULL,
    [Profile Seq Num]                          VARCHAR (16)  NULL,
    [Instrument Type]                          VARCHAR (50)  NULL,
    [Instrument Sub-Type]                      VARCHAR (50)  NULL,
    [Fixed/Float Flag]                         VARCHAR (1)   NULL,
    [Buy/Sell Flag deal detail/delivery month] VARCHAR (1)   NULL,
    [Volume Frequency]                         VARCHAR (1)   NULL,
    [Unit of Measure]                          VARCHAR (50)  NULL,
    [Price Currency ID]                        VARCHAR (50)  NULL,
    [Broker Name]                              VARCHAR (50)  NULL,
    [Legal Entity]                             VARCHAR (50)  NULL,
    [IntBunit]                                 VARCHAR (50)  NULL,
    [Ext Legal]                                VARCHAR (50)  NULL,
    [Ext Pfolio]                               VARCHAR (50)  NULL,
    [Option Type]                              VARCHAR (4)   NULL,
    [Option Strike]                            VARCHAR (58)  NULL,
    [Option Premium]                           VARCHAR (58)  NULL,
    [Premium Settlement Date]                  VARCHAR (10)  NULL,
    [Commentary]                               VARCHAR (250) NULL,
    [Product]                                  VARCHAR (50)  NULL,
    [Unit Of Measure2]                         VARCHAR (50)  NULL
);


GO

