CREATE TABLE [SAP_Dev].[/BIC/OHCVCORACEA_BAK] (
    [REQTSN]         NVARCHAR (23) NOT NULL,
    [DATAPAKID]      INT           NOT NULL,
    [RECORD]         INT           NOT NULL,
    [SOURSYSTEM]     NVARCHAR (2)  NOT NULL,
    [/BIC/CGLCOMPCD] NVARCHAR (4)  NOT NULL,
    [/BIC/CGCORACEA] NVARCHAR (10) NOT NULL,
    [/BIC/CGCORPOTY] NVARCHAR (4)  NOT NULL,
    [/BIC/CGCORMAP]  NVARCHAR (2)  NOT NULL,
    [/BIC/CGCORM1]   NVARCHAR (4)  NOT NULL,
    [/BIC/CGCORM2]   NVARCHAR (4)  NOT NULL,
    [/BIC/CGCORPO]   NVARCHAR (10) NOT NULL,
    [/BIC/CCARRACPO] NVARCHAR (12) NOT NULL
);


GO

