CREATE TABLE [SAP_QA].[/BIC/OHCVFIGLFIN_BAK] (
    [REQTSN]           NVARCHAR (23)    NOT NULL,
    [DATAPAKID]        INT              NOT NULL,
    [RECORD]           INT              NOT NULL,
    [RCLNT]            NVARCHAR (3)     NOT NULL,
    [RLDNR]            NVARCHAR (2)     NOT NULL,
    [RBUKRS]           NVARCHAR (4)     NOT NULL,
    [GJAHR]            NVARCHAR (4)     NOT NULL,
    [BELNR]            NVARCHAR (10)    NOT NULL,
    [DOCLN]            NVARCHAR (6)     NOT NULL,
    [RECORDMODE]       NVARCHAR (1)     NOT NULL,
    [RMVCT]            NVARCHAR (3)     NOT NULL,
    [VORGN]            NVARCHAR (4)     NOT NULL,
    [VRGNG]            NVARCHAR (4)     NOT NULL,
    [BTTYPE]           NVARCHAR (4)     NOT NULL,
    [CBTTYPE]          NVARCHAR (4)     NOT NULL,
    [AWTYP]            NVARCHAR (5)     NOT NULL,
    [AWSYS]            NVARCHAR (10)    NOT NULL,
    [AWORG]            NVARCHAR (10)    NOT NULL,
    [AWREF]            NVARCHAR (10)    NOT NULL,
    [AWITEM]           NVARCHAR (6)     NOT NULL,
    [AWITGRP]          NVARCHAR (6)     NOT NULL,
    [SUBTA]            NVARCHAR (6)     NOT NULL,
    [XREVERSING]       NVARCHAR (1)     NOT NULL,
    [XREVERSED]        NVARCHAR (1)     NOT NULL,
    [XTRUEREV]         NVARCHAR (1)     NOT NULL,
    [AWTYP_REV]        NVARCHAR (5)     NOT NULL,
    [AWORG_REV]        NVARCHAR (10)    NOT NULL,
    [AWREF_REV]        NVARCHAR (10)    NOT NULL,
    [AWITEM_REV]       NVARCHAR (6)     NOT NULL,
    [SUBTA_REV]        NVARCHAR (6)     NOT NULL,
    [XSETTLING]        NVARCHAR (1)     NOT NULL,
    [XSETTLED]         NVARCHAR (1)     NOT NULL,
    [PREC_AWTYP]       NVARCHAR (5)     NOT NULL,
    [PREC_AWSYS]       NVARCHAR (10)    NOT NULL,
    [PREC_AWORG]       NVARCHAR (10)    NOT NULL,
    [PREC_AWREF]       NVARCHAR (10)    NOT NULL,
    [PREC_AWITEM]      NVARCHAR (6)     NOT NULL,
    [PREC_SUBTA]       NVARCHAR (6)     NOT NULL,
    [PREC_AWMULT]      VARBINARY (16)   NULL,
    [PREC_BUKRS]       NVARCHAR (4)     NOT NULL,
    [PREC_GJAHR]       NVARCHAR (4)     NOT NULL,
    [PREC_BELNR]       NVARCHAR (10)    NOT NULL,
    [PREC_DOCLN]       NVARCHAR (6)     NOT NULL,
    [XSECONDARY]       NVARCHAR (1)     NOT NULL,
    [CLOSING_RUN_ID]   VARBINARY (16)   NULL,
    [ORGL_CHANGE]      NVARCHAR (10)    NOT NULL,
    [SRC_AWTYP]        NVARCHAR (5)     NOT NULL,
    [SRC_AWSYS]        NVARCHAR (10)    NOT NULL,
    [SRC_AWORG]        NVARCHAR (10)    NOT NULL,
    [SRC_AWREF]        NVARCHAR (10)    NOT NULL,
    [SRC_AWITEM]       NVARCHAR (6)     NOT NULL,
    [SRC_AWSUBIT]      NVARCHAR (6)     NOT NULL,
    [XCOMMITMENT]      NVARCHAR (1)     NOT NULL,
    [OBS_REASON]       NVARCHAR (1)     NOT NULL,
    [RTCUR]            NVARCHAR (5)     NOT NULL,
    [RWCUR]            NVARCHAR (5)     NOT NULL,
    [RHCUR]            NVARCHAR (5)     NOT NULL,
    [RKCUR]            NVARCHAR (5)     NOT NULL,
    [ROCUR]            NVARCHAR (5)     NOT NULL,
    [RVCUR]            NVARCHAR (5)     NOT NULL,
    [RBCUR]            NVARCHAR (5)     NOT NULL,
    [RCCUR]            NVARCHAR (5)     NOT NULL,
    [RDCUR]            NVARCHAR (5)     NOT NULL,
    [RECUR]            NVARCHAR (5)     NOT NULL,
    [RFCUR]            NVARCHAR (5)     NOT NULL,
    [RGCUR]            NVARCHAR (5)     NOT NULL,
    [RCO_OCUR]         NVARCHAR (5)     NOT NULL,
    [RGM_OCUR]         NVARCHAR (5)     NOT NULL,
    [RUNIT]            NVARCHAR (3)     NOT NULL,
    [RVUNIT]           NVARCHAR (3)     NOT NULL,
    [RRUNIT]           NVARCHAR (3)     NOT NULL,
    [RMSL_TYPE]        NVARCHAR (1)     NOT NULL,
    [RIUNIT]           NVARCHAR (3)     NOT NULL,
    [QUNIT1]           NVARCHAR (3)     NOT NULL,
    [QUNIT2]           NVARCHAR (3)     NOT NULL,
    [QUNIT3]           NVARCHAR (3)     NOT NULL,
    [CO_MEINH]         NVARCHAR (3)     NOT NULL,
    [RCNTR]            NVARCHAR (10)    NOT NULL,
    [PRCTR]            NVARCHAR (10)    NOT NULL,
    [RFAREA]           NVARCHAR (16)    NOT NULL,
    [RBUSA]            NVARCHAR (4)     NOT NULL,
    [KOKRS]            NVARCHAR (4)     NOT NULL,
    [SEGMENT]          NVARCHAR (10)    NOT NULL,
    [SCNTR]            NVARCHAR (10)    NOT NULL,
    [PPRCTR]           NVARCHAR (10)    NOT NULL,
    [SFAREA]           NVARCHAR (16)    NOT NULL,
    [SBUSA]            NVARCHAR (4)     NOT NULL,
    [RASSC]            NVARCHAR (6)     NOT NULL,
    [PSEGMENT]         NVARCHAR (10)    NOT NULL,
    [TSL]              DECIMAL (23, 2)  NOT NULL,
    [WSL]              DECIMAL (23, 2)  NOT NULL,
    [WSL2]             DECIMAL (23, 2)  NOT NULL,
    [WSL3]             DECIMAL (23, 2)  NOT NULL,
    [HSL]              DECIMAL (23, 2)  NOT NULL,
    [KSL]              DECIMAL (23, 2)  NOT NULL,
    [OSL]              DECIMAL (23, 2)  NOT NULL,
    [VSL]              DECIMAL (23, 2)  NOT NULL,
    [BSL]              DECIMAL (23, 2)  NOT NULL,
    [CSL]              DECIMAL (23, 2)  NOT NULL,
    [DSL]              DECIMAL (23, 2)  NOT NULL,
    [ESL]              DECIMAL (23, 2)  NOT NULL,
    [FSL]              DECIMAL (23, 2)  NOT NULL,
    [GSL]              DECIMAL (23, 2)  NOT NULL,
    [KFSL]             DECIMAL (23, 2)  NOT NULL,
    [KFSL2]            DECIMAL (23, 2)  NOT NULL,
    [KFSL3]            DECIMAL (23, 2)  NOT NULL,
    [PSL]              DECIMAL (23, 2)  NOT NULL,
    [PSL2]             DECIMAL (23, 2)  NOT NULL,
    [PSL3]             DECIMAL (23, 2)  NOT NULL,
    [PFSL]             DECIMAL (23, 2)  NOT NULL,
    [PFSL2]            DECIMAL (23, 2)  NOT NULL,
    [PFSL3]            DECIMAL (23, 2)  NOT NULL,
    [CO_OSL]           DECIMAL (23, 2)  NOT NULL,
    [GM_OSL]           DECIMAL (23, 2)  NOT NULL,
    [HSLALT]           DECIMAL (23, 2)  NOT NULL,
    [KSLALT]           DECIMAL (23, 2)  NOT NULL,
    [OSLALT]           DECIMAL (23, 2)  NOT NULL,
    [VSLALT]           DECIMAL (23, 2)  NOT NULL,
    [BSLALT]           DECIMAL (23, 2)  NOT NULL,
    [CSLALT]           DECIMAL (23, 2)  NOT NULL,
    [DSLALT]           DECIMAL (23, 2)  NOT NULL,
    [ESLALT]           DECIMAL (23, 2)  NOT NULL,
    [FSLALT]           DECIMAL (23, 2)  NOT NULL,
    [GSLALT]           DECIMAL (23, 2)  NOT NULL,
    [HSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [KSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [OSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [VSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [BSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [CSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [DSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [ESLEXT]           DECIMAL (23, 2)  NOT NULL,
    [FSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [GSLEXT]           DECIMAL (23, 2)  NOT NULL,
    [HVKWRT]           DECIMAL (23, 2)  NOT NULL,
    [MSL]              DECIMAL (23, 3)  NOT NULL,
    [MFSL]             DECIMAL (23, 3)  NOT NULL,
    [VMSL]             DECIMAL (23, 3)  NOT NULL,
    [VMFSL]            DECIMAL (23, 3)  NOT NULL,
    [RMSL]             DECIMAL (23, 3)  NOT NULL,
    [QUANT1]           DECIMAL (23, 3)  NOT NULL,
    [QUANT2]           DECIMAL (23, 3)  NOT NULL,
    [QUANT3]           DECIMAL (23, 3)  NOT NULL,
    [CO_MEGBTR]        DECIMAL (23, 3)  NOT NULL,
    [CO_MEFBTR]        DECIMAL (23, 3)  NOT NULL,
    [HSALK3]           DECIMAL (23, 2)  NOT NULL,
    [KSALK3]           DECIMAL (23, 2)  NOT NULL,
    [OSALK3]           DECIMAL (23, 2)  NOT NULL,
    [VSALK3]           DECIMAL (23, 2)  NOT NULL,
    [HSALKV]           DECIMAL (23, 2)  NOT NULL,
    [KSALKV]           DECIMAL (23, 2)  NOT NULL,
    [OSALKV]           DECIMAL (23, 2)  NOT NULL,
    [VSALKV]           DECIMAL (23, 2)  NOT NULL,
    [HPVPRS]           DECIMAL (23, 2)  NOT NULL,
    [KPVPRS]           DECIMAL (23, 2)  NOT NULL,
    [OPVPRS]           DECIMAL (23, 2)  NOT NULL,
    [VPVPRS]           DECIMAL (23, 2)  NOT NULL,
    [HSTPRS]           DECIMAL (23, 2)  NOT NULL,
    [KSTPRS]           DECIMAL (23, 2)  NOT NULL,
    [OSTPRS]           DECIMAL (23, 2)  NOT NULL,
    [VSTPRS]           DECIMAL (23, 2)  NOT NULL,
    [HVKSAL]           DECIMAL (23, 2)  NOT NULL,
    [LBKUM]            DECIMAL (23, 3)  NOT NULL,
    [DRCRK]            NVARCHAR (1)     NOT NULL,
    [POPER]            NVARCHAR (3)     NOT NULL,
    [PERIV]            NVARCHAR (2)     NOT NULL,
    [FISCYEARPER]      NVARCHAR (7)     NOT NULL,
    [BUDAT]            NVARCHAR (8)     NOT NULL,
    [BLDAT]            NVARCHAR (8)     NOT NULL,
    [BLART]            NVARCHAR (2)     NOT NULL,
    [BUZEI]            NVARCHAR (3)     NOT NULL,
    [ZUONR]            NVARCHAR (18)    NOT NULL,
    [BSCHL]            NVARCHAR (2)     NOT NULL,
    [BSTAT]            NVARCHAR (1)     NOT NULL,
    [LINETYPE]         NVARCHAR (5)     NOT NULL,
    [KTOSL]            NVARCHAR (3)     NOT NULL,
    [SLALITTYPE]       NVARCHAR (5)     NOT NULL,
    [XSPLITMOD]        NVARCHAR (1)     NOT NULL,
    [USNAM]            NVARCHAR (12)    NOT NULL,
    [TIMESTAMP]        DECIMAL (15)     NOT NULL,
    [EPRCTR]           NVARCHAR (10)    NOT NULL,
    [RHOART]           NVARCHAR (2)     NOT NULL,
    [GLACCOUNT_TYPE]   NVARCHAR (1)     NOT NULL,
    [KTOPL]            NVARCHAR (4)     NOT NULL,
    [LOKKT]            NVARCHAR (10)    NOT NULL,
    [KTOP2]            NVARCHAR (4)     NOT NULL,
    [REBZG]            NVARCHAR (10)    NOT NULL,
    [REBZJ]            NVARCHAR (4)     NOT NULL,
    [REBZZ]            NVARCHAR (3)     NOT NULL,
    [REBZT]            NVARCHAR (1)     NOT NULL,
    [RBEST]            NVARCHAR (3)     NOT NULL,
    [EBELN_LOGSYS]     NVARCHAR (10)    NOT NULL,
    [EBELN]            NVARCHAR (10)    NOT NULL,
    [EBELP]            NVARCHAR (5)     NOT NULL,
    [ZEKKN]            NVARCHAR (2)     NOT NULL,
    [SGTXT]            NVARCHAR (50)    NOT NULL,
    [KDAUF]            NVARCHAR (10)    NOT NULL,
    [KDPOS]            NVARCHAR (6)     NOT NULL,
    [MATNR]            NVARCHAR (40)    NOT NULL,
    [WERKS]            NVARCHAR (4)     NOT NULL,
    [LIFNR]            NVARCHAR (10)    NOT NULL,
    [KUNNR]            NVARCHAR (10)    NOT NULL,
    [FBUDA]            NVARCHAR (8)     NOT NULL,
    [PEROP_BEG]        NVARCHAR (8)     NOT NULL,
    [PEROP_END]        NVARCHAR (8)     NOT NULL,
    [COCO_NUM]         NVARCHAR (10)    NOT NULL,
    [WWERT]            NVARCHAR (8)     NOT NULL,
    [PRCTR_DRVTN_SRC]  NVARCHAR (2)     NOT NULL,
    [KOART]            NVARCHAR (1)     NOT NULL,
    [UMSKZ]            NVARCHAR (1)     NOT NULL,
    [TAX_COUNTRY]      NVARCHAR (3)     NOT NULL,
    [MWSKZ]            NVARCHAR (2)     NOT NULL,
    [HBKID]            NVARCHAR (5)     NOT NULL,
    [HKTID]            NVARCHAR (5)     NOT NULL,
    [VALUT]            NVARCHAR (8)     NOT NULL,
    [XOPVW]            NVARCHAR (1)     NOT NULL,
    [AUGDT]            NVARCHAR (8)     NOT NULL,
    [AUGBL]            NVARCHAR (10)    NOT NULL,
    [AUGGJ]            NVARCHAR (4)     NOT NULL,
    [AFABE]            NVARCHAR (2)     NOT NULL,
    [ANLN1]            NVARCHAR (12)    NOT NULL,
    [ANLN2]            NVARCHAR (4)     NOT NULL,
    [BZDAT]            NVARCHAR (8)     NOT NULL,
    [ANBWA]            NVARCHAR (3)     NOT NULL,
    [MOVCAT]           NVARCHAR (2)     NOT NULL,
    [DEPR_PERIOD]      NVARCHAR (3)     NOT NULL,
    [ANLGR]            NVARCHAR (12)    NOT NULL,
    [ANLGR2]           NVARCHAR (4)     NOT NULL,
    [SETTLEMENT_RULE]  NVARCHAR (3)     NOT NULL,
    [ANLKL]            NVARCHAR (8)     NOT NULL,
    [KTOGR]            NVARCHAR (8)     NOT NULL,
    [PANL1]            NVARCHAR (12)    NOT NULL,
    [PANL2]            NVARCHAR (4)     NOT NULL,
    [UBZDT_PN]         NVARCHAR (8)     NOT NULL,
    [XVABG_PN]         NVARCHAR (1)     NOT NULL,
    [PROZS_PN]         DECIMAL (5, 2)   NOT NULL,
    [XMANPROPVAL_PN]   NVARCHAR (1)     NOT NULL,
    [KALNR]            NVARCHAR (12)    NOT NULL,
    [VPRSV]            NVARCHAR (1)     NOT NULL,
    [MLAST]            NVARCHAR (1)     NOT NULL,
    [KZBWS]            NVARCHAR (1)     NOT NULL,
    [XOBEW]            NVARCHAR (1)     NOT NULL,
    [SOBKZ]            NVARCHAR (1)     NOT NULL,
    [VTSTAMP]          DECIMAL (21, 7)  NOT NULL,
    [MAT_KDAUF]        NVARCHAR (10)    NOT NULL,
    [MAT_KDPOS]        NVARCHAR (6)     NOT NULL,
    [MAT_PSPNR]        NVARCHAR (8)     NOT NULL,
    [MAT_PS_POSID]     NVARCHAR (24)    NOT NULL,
    [MAT_LIFNR]        NVARCHAR (10)    NOT NULL,
    [BWTAR]            NVARCHAR (10)    NOT NULL,
    [BWKEY]            NVARCHAR (4)     NOT NULL,
    [HPEINH]           DECIMAL (5)      NOT NULL,
    [KPEINH]           DECIMAL (5)      NOT NULL,
    [OPEINH]           DECIMAL (5)      NOT NULL,
    [VPEINH]           DECIMAL (5)      NOT NULL,
    [MLPTYP]           NVARCHAR (4)     NOT NULL,
    [MLCATEG]          NVARCHAR (2)     NOT NULL,
    [QSBVALT]          NVARCHAR (12)    NOT NULL,
    [QSPROCESS]        NVARCHAR (12)    NOT NULL,
    [PERART]           NVARCHAR (2)     NOT NULL,
    [MLPOSNR]          NVARCHAR (6)     NOT NULL,
    [INV_MOV_CATEG]    NVARCHAR (1)     NOT NULL,
    [BUKRS_SENDER]     NVARCHAR (4)     NOT NULL,
    [RACCT_SENDER]     NVARCHAR (10)    NOT NULL,
    [ACCAS_SENDER]     NVARCHAR (30)    NOT NULL,
    [ACCASTY_SENDER]   NVARCHAR (2)     NOT NULL,
    [OBJNR]            NVARCHAR (22)    NOT NULL,
    [HRKFT]            NVARCHAR (14)    NOT NULL,
    [HKGRP]            NVARCHAR (4)     NOT NULL,
    [PAROB1]           NVARCHAR (22)    NOT NULL,
    [PAROBSRC]         NVARCHAR (1)     NOT NULL,
    [USPOB]            NVARCHAR (22)    NOT NULL,
    [CO_BELKZ]         NVARCHAR (1)     NOT NULL,
    [CO_BEKNZ]         NVARCHAR (1)     NOT NULL,
    [BELTP]            NVARCHAR (1)     NOT NULL,
    [MUVFLG]           NVARCHAR (1)     NOT NULL,
    [GKONT]            NVARCHAR (10)    NOT NULL,
    [GKOAR]            NVARCHAR (1)     NOT NULL,
    [ERLKZ]            NVARCHAR (1)     NOT NULL,
    [PERNR]            NVARCHAR (8)     NOT NULL,
    [PAOBJNR]          NVARCHAR (10)    NOT NULL,
    [XPAOBJNR_CO_REL]  NVARCHAR (1)     NOT NULL,
    [SCOPE]            NVARCHAR (2)     NOT NULL,
    [LOGSYSO]          NVARCHAR (10)    NOT NULL,
    [PBUKRS]           NVARCHAR (4)     NOT NULL,
    [PSCOPE]           NVARCHAR (2)     NOT NULL,
    [LOGSYSP]          NVARCHAR (10)    NOT NULL,
    [BWSTRAT]          NVARCHAR (1)     NOT NULL,
    [OBJNR_HK]         NVARCHAR (22)    NOT NULL,
    [AUFNR_ORG]        NVARCHAR (12)    NOT NULL,
    [UKOSTL]           NVARCHAR (10)    NOT NULL,
    [ULSTAR]           NVARCHAR (6)     NOT NULL,
    [UPRZNR]           NVARCHAR (12)    NOT NULL,
    [UPRCTR]           NVARCHAR (10)    NOT NULL,
    [UMATNR]           NVARCHAR (40)    NOT NULL,
    [VARC_UACCT]       NVARCHAR (10)    NOT NULL,
    [ACCAS]            NVARCHAR (30)    NOT NULL,
    [ACCASTY]          NVARCHAR (2)     NOT NULL,
    [LSTAR]            NVARCHAR (6)     NOT NULL,
    [AUFNR]            NVARCHAR (12)    NOT NULL,
    [AUTYP]            NVARCHAR (2)     NOT NULL,
    [PS_PSP_PNR]       NVARCHAR (8)     NOT NULL,
    [PS_POSID]         NVARCHAR (24)    NOT NULL,
    [PS_PRJ_PNR]       NVARCHAR (8)     NOT NULL,
    [PS_PSPID]         NVARCHAR (24)    NOT NULL,
    [NPLNR]            NVARCHAR (12)    NOT NULL,
    [NPLNR_VORGN]      NVARCHAR (4)     NOT NULL,
    [PRZNR]            NVARCHAR (12)    NOT NULL,
    [KSTRG]            NVARCHAR (12)    NOT NULL,
    [BEMOT]            NVARCHAR (2)     NOT NULL,
    [RSRCE]            NVARCHAR (10)    NOT NULL,
    [QMNUM]            NVARCHAR (12)    NOT NULL,
    [SERVICE_DOC_TYPE] NVARCHAR (4)     NOT NULL,
    [SERVICE_DOC_ID]   NVARCHAR (10)    NOT NULL,
    [SRVC_DOC_ITM_ID]  NVARCHAR (6)     NOT NULL,
    [SRVC_CNTRCT_TYP]  NVARCHAR (4)     NOT NULL,
    [SRVC_CONTRCT_ID]  NVARCHAR (10)    NOT NULL,
    [SRVCCONTRCTITMID] NVARCHAR (6)     NOT NULL,
    [SOLUTN_ORDR_ID]   NVARCHAR (10)    NOT NULL,
    [SOLUTNORDRITMID]  NVARCHAR (6)     NOT NULL,
    [ERKRS]            NVARCHAR (4)     NOT NULL,
    [PACCAS]           NVARCHAR (30)    NOT NULL,
    [PACCASTY]         NVARCHAR (2)     NOT NULL,
    [PLSTAR]           NVARCHAR (6)     NOT NULL,
    [PAUFNR]           NVARCHAR (12)    NOT NULL,
    [PAUTYP]           NVARCHAR (2)     NOT NULL,
    [PPS_PSP_PNR]      NVARCHAR (8)     NOT NULL,
    [PPS_POSID]        NVARCHAR (24)    NOT NULL,
    [PPS_PRJ_PNR]      NVARCHAR (8)     NOT NULL,
    [PPS_PSPID]        NVARCHAR (24)    NOT NULL,
    [PKDAUF]           NVARCHAR (10)    NOT NULL,
    [PKDPOS]           NVARCHAR (6)     NOT NULL,
    [PPAOBJNR]         NVARCHAR (10)    NOT NULL,
    [PNPLNR]           NVARCHAR (12)    NOT NULL,
    [PNPLNR_VORGN]     NVARCHAR (4)     NOT NULL,
    [PPRZNR]           NVARCHAR (12)    NOT NULL,
    [PKSTRG]           NVARCHAR (12)    NOT NULL,
    [PSRV_DOC_TYPE]    NVARCHAR (4)     NOT NULL,
    [PSRV_DOC_ID]      NVARCHAR (10)    NOT NULL,
    [PSRV_DOC_ITM_ID]  NVARCHAR (6)     NOT NULL,
    [CO_ACCASTY_N1]    NVARCHAR (2)     NOT NULL,
    [CO_ACCASTY_N2]    NVARCHAR (2)     NOT NULL,
    [CO_ACCASTY_N3]    NVARCHAR (2)     NOT NULL,
    [CO_ZLENR]         NVARCHAR (3)     NOT NULL,
    [CO_BELNR]         NVARCHAR (10)    NOT NULL,
    [CO_BUZEI]         NVARCHAR (3)     NOT NULL,
    [CO_BUZEI1]        NVARCHAR (3)     NOT NULL,
    [CO_BUZEI2]        NVARCHAR (3)     NOT NULL,
    [CO_BUZEI5]        NVARCHAR (3)     NOT NULL,
    [CO_BUZEI6]        NVARCHAR (3)     NOT NULL,
    [CO_BUZEI7]        NVARCHAR (3)     NOT NULL,
    [CO_REFBZ]         NVARCHAR (3)     NOT NULL,
    [CO_REFBZ1]        NVARCHAR (3)     NOT NULL,
    [CO_REFBZ2]        NVARCHAR (3)     NOT NULL,
    [CO_REFBZ5]        NVARCHAR (3)     NOT NULL,
    [CO_REFBZ6]        NVARCHAR (3)     NOT NULL,
    [CO_REFBZ7]        NVARCHAR (3)     NOT NULL,
    [OVERTIMECAT]      NVARCHAR (4)     NOT NULL,
    [WORK_ITEM_ID]     NVARCHAR (10)    NOT NULL,
    [FKART]            NVARCHAR (4)     NOT NULL,
    [VKORG]            NVARCHAR (4)     NOT NULL,
    [VTWEG]            NVARCHAR (2)     NOT NULL,
    [SPART]            NVARCHAR (2)     NOT NULL,
    [MATNR_COPA]       NVARCHAR (40)    NOT NULL,
    [MATKL]            NVARCHAR (9)     NOT NULL,
    [KDGRP]            NVARCHAR (2)     NOT NULL,
    [LAND1]            NVARCHAR (3)     NOT NULL,
    [BRSCH]            NVARCHAR (4)     NOT NULL,
    [BZIRK]            NVARCHAR (6)     NOT NULL,
    [KUNRE]            NVARCHAR (10)    NOT NULL,
    [KUNWE]            NVARCHAR (10)    NOT NULL,
    [KONZS]            NVARCHAR (10)    NOT NULL,
    [WWAOR_PA]         NVARCHAR (10)    NOT NULL,
    [DMRKTSGMNTEEWPS]  NVARCHAR (1)     NOT NULL,
    [RE_BUKRS]         NVARCHAR (4)     NOT NULL,
    [RE_ACCOUNT]       NVARCHAR (10)    NOT NULL,
    [FIKRS]            NVARCHAR (4)     NOT NULL,
    [FIPEX]            NVARCHAR (24)    NOT NULL,
    [FISTL]            NVARCHAR (16)    NOT NULL,
    [MEASURE]          NVARCHAR (24)    NOT NULL,
    [RFUND]            NVARCHAR (10)    NOT NULL,
    [RGRANT_NBR]       NVARCHAR (20)    NOT NULL,
    [RBUDGET_PD]       NVARCHAR (10)    NOT NULL,
    [SFUND]            NVARCHAR (10)    NOT NULL,
    [SGRANT_NBR]       NVARCHAR (20)    NOT NULL,
    [SBUDGET_PD]       NVARCHAR (10)    NOT NULL,
    [BDGT_ACNT]        NVARCHAR (10)    NOT NULL,
    [BDGT_ACNT_COCDE]  NVARCHAR (4)     NOT NULL,
    [BDGT_CNSMPN_DAT]  NVARCHAR (8)     NOT NULL,
    [BDGT_CNSMPN_PRD]  NVARCHAR (3)     NOT NULL,
    [BDGT_CNSMPN_YER]  NVARCHAR (4)     NOT NULL,
    [BDGT_RELEVANT]    NVARCHAR (1)     NOT NULL,
    [BDGT_CNSMPN_TYP]  NVARCHAR (2)     NOT NULL,
    [BDGTCNSMPNAMTTP]  NVARCHAR (4)     NOT NULL,
    [RSPONSORED_PROG]  NVARCHAR (20)    NOT NULL,
    [RSPONSORED_CLASS] NVARCHAR (20)    NOT NULL,
    [RBDGT_VLDTY_NBR]  NVARCHAR (3)     NOT NULL,
    [KBLNR]            NVARCHAR (10)    NOT NULL,
    [KBLPOS]           NVARCHAR (3)     NOT NULL,
    [VNAME]            NVARCHAR (6)     NOT NULL,
    [EGRUP]            NVARCHAR (3)     NOT NULL,
    [RECID]            NVARCHAR (2)     NOT NULL,
    [VPTNR]            NVARCHAR (10)    NOT NULL,
    [BTYPE]            NVARCHAR (2)     NOT NULL,
    [ETYPE]            NVARCHAR (3)     NOT NULL,
    [PRODPER]          NVARCHAR (8)     NOT NULL,
    [BILLM]            NVARCHAR (8)     NOT NULL,
    [POM]              NVARCHAR (8)     NOT NULL,
    [CBRUNID]          DECIMAL (21, 7)  NOT NULL,
    [JVACTIVITY]       NVARCHAR (2)     NOT NULL,
    [PVNAME]           NVARCHAR (6)     NOT NULL,
    [PEGRUP]           NVARCHAR (3)     NOT NULL,
    [S_RECIND]         NVARCHAR (2)     NOT NULL,
    [CBRACCT]          NVARCHAR (10)    NOT NULL,
    [CBOBJNR]          NVARCHAR (22)    NOT NULL,
    [SWENR]            NVARCHAR (8)     NOT NULL,
    [SGENR]            NVARCHAR (8)     NOT NULL,
    [SGRNR]            NVARCHAR (8)     NOT NULL,
    [SMENR]            NVARCHAR (8)     NOT NULL,
    [RECNNR]           NVARCHAR (13)    NOT NULL,
    [SNKSL]            NVARCHAR (4)     NOT NULL,
    [SEMPSL]           NVARCHAR (5)     NOT NULL,
    [DABRZ]            NVARCHAR (8)     NOT NULL,
    [PSWENR]           NVARCHAR (8)     NOT NULL,
    [PSGENR]           NVARCHAR (8)     NOT NULL,
    [PSGRNR]           NVARCHAR (8)     NOT NULL,
    [PSMENR]           NVARCHAR (8)     NOT NULL,
    [PRECNNR]          NVARCHAR (13)    NOT NULL,
    [PSNKSL]           NVARCHAR (4)     NOT NULL,
    [PSEMPSL]          NVARCHAR (5)     NOT NULL,
    [PDABRZ]           NVARCHAR (8)     NOT NULL,
    [ACDOC_EEW_DUMMY]  NVARCHAR (1)     NOT NULL,
    [DM_INCL_EEW_CBL]  NVARCHAR (1)     NOT NULL,
    [ZZ_LOCATION]      NVARCHAR (1)     NOT NULL,
    [ZZ_COUNTRY]       NVARCHAR (4)     NOT NULL,
    [ZZ_TAX_INFO]      NVARCHAR (35)    NOT NULL,
    [ZZ_TAX]           NVARCHAR (35)    NOT NULL,
    [ZVBEWA]           NVARCHAR (4)     NOT NULL,
    [ZXREF1]           NVARCHAR (12)    NOT NULL,
    [ZXREF2]           NVARCHAR (12)    NOT NULL,
    [ZXREF3]           NVARCHAR (20)    NOT NULL,
    [MIG_SOURCE]       NVARCHAR (1)     NOT NULL,
    [MIG_DOCLN]        NVARCHAR (6)     NOT NULL,
    [UPMOD]            NVARCHAR (1)     NOT NULL,
    [RYEAR]            NVARCHAR (4)     NOT NULL,
    [RRCTY]            NVARCHAR (1)     NOT NULL,
    [RACCT]            NVARCHAR (10)    NOT NULL,
    [ODQ_CHANGEMODE]   NVARCHAR (1)     NOT NULL,
    [ODQ_ENTITYCNTR]   DECIMAL (19)     NOT NULL,
    [BKPF_BUKRS]       NVARCHAR (4)     NOT NULL,
    [BKPF_BELNR]       NVARCHAR (10)    NOT NULL,
    [BKPF_GJAHR]       NVARCHAR (4)     NOT NULL,
    [BKPF_RECORDMODE]  NVARCHAR (1)     NOT NULL,
    [BKPF_BLART]       NVARCHAR (2)     NOT NULL,
    [BKPF_BLDAT]       NVARCHAR (8)     NOT NULL,
    [BKPF_BUDAT]       NVARCHAR (8)     NOT NULL,
    [BKPF_MONAT]       NVARCHAR (2)     NOT NULL,
    [BKPF_CPUDT]       NVARCHAR (8)     NOT NULL,
    [BKPF_CPUTM]       NVARCHAR (6)     NOT NULL,
    [BKPF_AEDAT]       NVARCHAR (8)     NOT NULL,
    [BKPF_UPDDT]       NVARCHAR (8)     NOT NULL,
    [BKPF_WWERT]       NVARCHAR (8)     NOT NULL,
    [BKPF_USNAM]       NVARCHAR (12)    NOT NULL,
    [BKPF_TCODE]       NVARCHAR (20)    NOT NULL,
    [BKPF_BVORG]       NVARCHAR (16)    NOT NULL,
    [BKPF_XBLNR]       NVARCHAR (16)    NOT NULL,
    [BKPF_DBBLG]       NVARCHAR (10)    NOT NULL,
    [BKPF_DBBLGGJAHR]  NVARCHAR (4)     NOT NULL,
    [BKPF_DBBLGBUKRS]  NVARCHAR (4)     NOT NULL,
    [BKPF_STBLG]       NVARCHAR (10)    NOT NULL,
    [BKPF_STJAH]       NVARCHAR (4)     NOT NULL,
    [BKPF_BKTXT]       NVARCHAR (25)    NOT NULL,
    [BKPF_WAERS]       NVARCHAR (5)     NOT NULL,
    [BKPF_KURSF]       DECIMAL (17, 5)  NOT NULL,
    [BKPF_KZWRS]       NVARCHAR (5)     NOT NULL,
    [BKPF_KZKRS]       DECIMAL (17, 5)  NOT NULL,
    [BKPF_BSTAT]       NVARCHAR (1)     NOT NULL,
    [BKPF_XNETB]       NVARCHAR (1)     NOT NULL,
    [BKPF_FRATH]       DECIMAL (17, 2)  NOT NULL,
    [BKPF_XRUEB]       NVARCHAR (1)     NOT NULL,
    [BKPF_GLVOR]       NVARCHAR (4)     NOT NULL,
    [BKPF_GRPID]       NVARCHAR (12)    NOT NULL,
    [BKPF_DOKID]       NVARCHAR (40)    NOT NULL,
    [BKPF_ARCID]       NVARCHAR (10)    NOT NULL,
    [BKPF_IBLAR]       NVARCHAR (2)     NOT NULL,
    [BKPF_AWTYP]       NVARCHAR (5)     NOT NULL,
    [BKPF_AWKEY]       NVARCHAR (20)    NOT NULL,
    [BKPF_FIKRS]       NVARCHAR (4)     NOT NULL,
    [BKPF_HWAER]       NVARCHAR (5)     NOT NULL,
    [BKPF_HWAE2]       NVARCHAR (5)     NOT NULL,
    [BKPF_HWAE3]       NVARCHAR (5)     NOT NULL,
    [BKPF_KURS2]       DECIMAL (17, 5)  NOT NULL,
    [BKPF_KURS3]       DECIMAL (17, 5)  NOT NULL,
    [BKPF_BASW2]       NVARCHAR (1)     NOT NULL,
    [BKPF_BASW3]       NVARCHAR (1)     NOT NULL,
    [BKPF_UMRD2]       NVARCHAR (1)     NOT NULL,
    [BKPF_UMRD3]       NVARCHAR (1)     NOT NULL,
    [BKPF_XSTOV]       NVARCHAR (1)     NOT NULL,
    [BKPF_STODT]       NVARCHAR (8)     NOT NULL,
    [BKPF_XMWST]       NVARCHAR (1)     NOT NULL,
    [BKPF_CURT2]       NVARCHAR (2)     NOT NULL,
    [BKPF_CURT3]       NVARCHAR (2)     NOT NULL,
    [BKPF_KUTY2]       NVARCHAR (4)     NOT NULL,
    [BKPF_KUTY3]       NVARCHAR (4)     NOT NULL,
    [BKPF_XSNET]       NVARCHAR (1)     NOT NULL,
    [BKPF_AUSBK]       NVARCHAR (4)     NOT NULL,
    [BKPF_XUSVR]       NVARCHAR (1)     NOT NULL,
    [BKPF_DUEFL]       NVARCHAR (1)     NOT NULL,
    [BKPF_AWSYS]       NVARCHAR (10)    NOT NULL,
    [BKPF_TXKRS]       DECIMAL (17, 5)  NOT NULL,
    [BKPF_CTXKRS]      DECIMAL (17, 5)  NOT NULL,
    [BKPF_LOTKZ]       NVARCHAR (10)    NOT NULL,
    [BKPF_XWVOF]       NVARCHAR (1)     NOT NULL,
    [BKPF_STGRD]       NVARCHAR (2)     NOT NULL,
    [BKPF_PPNAM]       NVARCHAR (12)    NOT NULL,
    [BKPF_PPDAT]       NVARCHAR (8)     NOT NULL,
    [BKPF_PPTME]       NVARCHAR (6)     NOT NULL,
    [BKPF_PPTCOD]      NVARCHAR (20)    NOT NULL,
    [BKPF_BRNCH]       NVARCHAR (4)     NOT NULL,
    [BKPF_NUMPG]       NVARCHAR (3)     NOT NULL,
    [BKPF_ADISC]       NVARCHAR (1)     NOT NULL,
    [BKPF_XREF1HD]     NVARCHAR (20)    NOT NULL,
    [BKPF_XREF2HD]     NVARCHAR (20)    NOT NULL,
    [BKPF_XREVERSAL]   NVARCHAR (1)     NOT NULL,
    [BKPF_REINDAT]     NVARCHAR (8)     NOT NULL,
    [BKPF_RLDNR]       NVARCHAR (2)     NOT NULL,
    [BKPF_LDGRP]       NVARCHAR (4)     NOT NULL,
    [BKPF_PROPMANO]    NVARCHAR (13)    NOT NULL,
    [BKPF_XBLNRALT]    NVARCHAR (26)    NOT NULL,
    [BKPF_VATDATE]     NVARCHAR (8)     NOT NULL,
    [BKPF_FULFILLDATE] NVARCHAR (8)     NOT NULL,
    [BKPF_DOCCAT]      NVARCHAR (6)     NOT NULL,
    [BKPF_XSPLIT]      NVARCHAR (1)     NOT NULL,
    [BKPF_CASHALLOC]   NVARCHAR (1)     NOT NULL,
    [BKPF_FOLLOWON]    NVARCHAR (1)     NOT NULL,
    [BKPF_XREORG]      NVARCHAR (1)     NOT NULL,
    [BKPF_SUBSET]      NVARCHAR (4)     NOT NULL,
    [BKPF_KURST]       NVARCHAR (4)     NOT NULL,
    [BKPF_KURSX]       DECIMAL (29, 14) NOT NULL,
    [BKPF_KUR2X]       DECIMAL (29, 14) NOT NULL,
    [BKPF_KUR3X]       DECIMAL (29, 14) NOT NULL,
    [BKPF_XMCA]        NVARCHAR (1)     NOT NULL,
    [BKPF_RESUBMISN]   NVARCHAR (8)     NOT NULL,
    [BKPF_LOGSYSSNDR]  NVARCHAR (10)    NOT NULL,
    [BKPF_BUKRSSENDER] NVARCHAR (4)     NOT NULL,
    [BKPF_BELNRSENDER] NVARCHAR (10)    NOT NULL,
    [BKPF_GJAHRSENDER] NVARCHAR (4)     NOT NULL,
    [BKPF_INTSUBID]    NVARCHAR (6)     NOT NULL,
    [BKPF_AWORGREV]    NVARCHAR (10)    NOT NULL,
    [BKPF_AWREFREV]    NVARCHAR (10)    NOT NULL,
    [BKPF_XREVERSING]  NVARCHAR (1)     NOT NULL,
    [BKPF_XREVERSED]   NVARCHAR (1)     NOT NULL,
    [BKPF_GLBTGRP]     NVARCHAR (1)     NOT NULL,
    [BKPF_COVRGNG]     NVARCHAR (4)     NOT NULL,
    [BKPF_COREFBT]     NVARCHAR (1)     NOT NULL,
    [BKPF_COALEBN]     NVARCHAR (10)    NOT NULL,
    [BKPF_COVALDT]     NVARCHAR (8)     NOT NULL,
    [BKPF_COBLNRSNDR]  NVARCHAR (10)    NOT NULL,
    [BKPF_KOKRSSENDER] NVARCHAR (4)     NOT NULL,
    [BKPF_ACPRINCIPL]  NVARCHAR (4)     NOT NULL,
    [BKPF_DATAAGING]   NVARCHAR (8)     NOT NULL,
    [BKPF_TRAVAPN]     NVARCHAR (4)     NOT NULL,
    [BKPF_LDGRPSPECPN] NVARCHAR (1)     NOT NULL,
    [BKPF_AFABESPCPN]  NVARCHAR (1)     NOT NULL,
    [BKPF_XSECONDARY]  NVARCHAR (1)     NOT NULL,
    [BKPF_REPRCSTACD]  NVARCHAR (1)     NOT NULL,
    [BKPF_TRRPARTIND]  NVARCHAR (1)     NOT NULL,
    [BKPF_ITMRMOVSTAT] NVARCHAR (1)     NOT NULL,
    [BKPF_PENRC]       NVARCHAR (2)     NOT NULL,
    [BKPF_GLOREF1HD]   NVARCHAR (80)    NOT NULL,
    [BKPF_GLODAT1HD]   NVARCHAR (8)     NOT NULL,
    [BKPF_GLOREF2HD]   NVARCHAR (25)    NOT NULL,
    [BKPF_GLODAT2HD]   NVARCHAR (8)     NOT NULL,
    [BKPF_GLOREF3HD]   NVARCHAR (25)    NOT NULL,
    [BKPF_GLODAT3HD]   NVARCHAR (8)     NOT NULL,
    [BKPF_GLOREF4HD]   NVARCHAR (50)    NOT NULL,
    [BKPF_GLODAT4HD]   NVARCHAR (8)     NOT NULL,
    [BKPF_GLOREF5HD]   NVARCHAR (50)    NOT NULL,
    [BKPF_GLODAT5HD]   NVARCHAR (8)     NOT NULL,
    [BKPF_GLOBP1HD]    NVARCHAR (10)    NOT NULL,
    [BKPF_GLOBP2HD]    NVARCHAR (10)    NOT NULL,
    [BKPF_EVPSTNGCTR]  NVARCHAR (1)     NOT NULL,
    [BKPF_WHTDATE]     NVARCHAR (8)     NOT NULL,
    [BKPF_CBTTYPE]     NVARCHAR (4)     NOT NULL,
    [BKPF_CLOSINGSTEP] NVARCHAR (3)     NOT NULL,
    [BKPF_XDIFLDGRVAL] NVARCHAR (1)     NOT NULL,
    [BKPF_XLDGRMISNG]  NVARCHAR (1)     NOT NULL,
    [BKPF_XUNIQVTYPS]  NVARCHAR (1)     NOT NULL,
    [BKPF_TAXCNTRYHD]  NVARCHAR (3)     NOT NULL,
    [BKPF_ANXTYPE]     NVARCHAR (1)     NOT NULL,
    [BKPF_ANXAMNT]     DECIMAL (17, 2)  NOT NULL,
    [BKPF_ANXPERC]     DECIMAL (17, 3)  NOT NULL,
    [BKPF_ZVATINDC]    NVARCHAR (8)     NOT NULL,
    [BKPF_STATUS]      NVARCHAR (1)     NOT NULL,
    [BKPF_PSOTY]       NVARCHAR (2)     NOT NULL,
    [BKPF_PSOAK]       NVARCHAR (10)    NOT NULL,
    [BKPF_PSOKS]       NVARCHAR (10)    NOT NULL,
    [BKPF_PSOSG]       NVARCHAR (1)     NOT NULL,
    [BKPF_PSOFN]       NVARCHAR (30)    NOT NULL,
    [BKPF_INTFORM]     NVARCHAR (4)     NOT NULL,
    [BKPF_INTDATE]     NVARCHAR (8)     NOT NULL,
    [BKPF_PSOBT]       NVARCHAR (8)     NOT NULL,
    [BKPF_PSOZL]       NVARCHAR (1)     NOT NULL,
    [BKPF_PSODT]       NVARCHAR (8)     NOT NULL,
    [BKPF_PSOTM]       NVARCHAR (6)     NOT NULL,
    [BKPF_FMUMART]     NVARCHAR (1)     NOT NULL,
    [BKPF_CCINS]       NVARCHAR (4)     NOT NULL,
    [BKPF_CCNUM]       NVARCHAR (25)    NOT NULL,
    [BKPF_SSBLK]       NVARCHAR (1)     NOT NULL,
    [BKPF_BATCH]       NVARCHAR (10)    NOT NULL,
    [BKPF_SNAME]       NVARCHAR (12)    NOT NULL,
    [BKPF_SAMPLED]     NVARCHAR (1)     NOT NULL,
    [BKPF_EXCLUDFLAG]  NVARCHAR (1)     NOT NULL,
    [BKPF_BLIND]       NVARCHAR (1)     NOT NULL,
    [BKPF_OFSTSTAT]    NVARCHAR (2)     NOT NULL,
    [BKPF_OFSTREFDAT]  NVARCHAR (8)     NOT NULL,
    [BKPF_KNUMV]       NVARCHAR (10)    NOT NULL,
    [BKPF_BLO]         NVARCHAR (1)     NOT NULL,
    [BKPF_CNT]         NVARCHAR (10)    NOT NULL,
    [BKPF_PYBASTYP]    NVARCHAR (2)     NOT NULL,
    [BKPF_PYBASNO]     NVARCHAR (16)    NOT NULL,
    [BKPF_PYBASDAT]    NVARCHAR (8)     NOT NULL,
    [BKPF_PYIBAN]      NVARCHAR (34)    NOT NULL,
    [BKPF_INWARDNOHD]  NVARCHAR (30)    NOT NULL,
    [BKPF_INWARDDTHD]  NVARCHAR (8)     NOT NULL,
    [BKPF_ODQ_CHMOD]   NVARCHAR (1)     NOT NULL,
    [BKPF_ODQ_ENTYCNT] DECIMAL (19)     NOT NULL
);


GO

